# -*- coding: utf-8 -*-
"""
AI 教师 · 英语课件批量生成脚本
依据《AI教师-课件制作指导文档》：每个知识点一份独立 HTML 课件（五段式步骤播放器），
复用 assets/player-core.js + assets/english-ui.js，零外部依赖，双击即开。

运行：python3 tools/gen_english_course.py
输出：英语/*.html（24 个课件）+ 控制台打印 knowledge-base.js 需新增/修改的条目
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "英语")

# ---------------------------------------------------------------- 数据
# 各单元字段说明见 assets/english-ui.js 头部注释
UNITS = [

# ============================ 三年级上册 ============================
dict(
  id="english-3-001", grade=3, term="上册", unit="Unit 1 Myself",
  file_unit="Unit1-Myself", title="认识我自己", module="vocab", difficulty="基础",
  summary="用英语介绍自己的名字和年龄",
  keywords=["Myself", "介绍", "名字", "年龄", "自我介绍"],
  prereq=[], fileName="英语-三上-Unit1-Myself-english-3-001-认识我自己.html",
  scene=dict(h2="新朋友 Binbin", text="开学啦，班里来了一位新同学，他叫 Binbin。他只会说英语，想和你交朋友。今天我们帮他学会用英语介绍自己。",
             question="想一想：你会用英语说「我叫…」「我八岁」吗？", hint="先想一想，下一步看看 Binbin 怎么说～"),
  s1_task="咱们这一步要做的：看看新朋友 Binbin 是怎么介绍自己的！",
  s1_voice="开学啦，班里来了一位新同学，他叫 Binbin。他只会说英语，想和你交朋友。今天我们要学会用英语介绍自己：你叫什么名字，你几岁了。你猜，Binbin 会怎么说？",
  words_title="单词大本营：我自己", words_intro="这些单词都和你自己有关。点一点卡片听发音，再跟着读一读！",
  s2_task="这一步我们要做的：认识介绍自己的单词，点卡片听发音！",
  s2_voice="这一单元我们来认识几个和自己有关的单词。点一点卡片，可以听到发音，跟着老师读一读吧。",
  words=[dict(e="my", z="我的", em="🙋"), dict(e="name", z="名字", em="📛"), dict(e="new", z="新的", em="✨"),
         dict(e="class", z="班级", em="🏫"), dict(e="old", z="几岁", em="🎂"), dict(e="school", z="学校", em="🏫"),
         dict(e="year", z="年；岁数", em="📅"), dict(e="number", z="号码", em="🔢")],
  pattern=dict(title="句型魔法：介绍自己", sentence=["My", "name", "is", "Binbin", "."], zh="我的名字是彬彬。",
               desc="What's your name? 你叫什么名字？ ｜ My name is Binbin. 我叫彬彬。 ｜ I'm eight years old. 我八岁啦。"),
  order=dict(zh="帮 Binbin 把自我介绍按顺序排好", words=["My", "name", "is", "Binbin", "."], right=[0, 1, 2, 3, 4],
             hint="句子开头是 My，中间记住 name is，最后加名字和句号～"),
  s3_task="这一步我们要做的：看句子怎么拼起来，再亲手把自我介绍排出来！",
  s3_voice="介绍自己的时候，我们先说 My name is，再加上自己的名字。看，句子就是这样一块一块拼出来的。现在轮到你了，把词块按顺序点成正确的句子吧！",
  quiz=[dict(q="「你叫什么名字？」用英语怎么说？", opts=["What's your name?", "My name is Binbin.", "How old are you?"], ok=0, hint="问名字用 What's your name?"),
        dict(q="「我八岁了。」用英语怎么说？", opts=["I'm eight years old.", "I'm eight.", "My name is eight."], ok=0, hint="说年龄用 I'm ... years old."),
        dict(q="name 的意思是？", opts=["名字", "年龄", "班级"], ok=0, hint="name 是「名字」哦")],
  s4_task="这一步我们要做的：连闯三道小题，把介绍自己的句子用起来！",
  s4_voice="现在轮到你啦！一共三道小题，看看你掌握了没有。答对就能得到星星哦。",
  summary_points=[["自我介绍三件套", "My name is ... 我的名字是…；I'm ... years old. 我…岁了；I'm in Class ... 我在…班。"],
                  ["怎么问名字", "What's your name? 你叫什么名字？"],
                  ["别记混", "name 是名字，number 是号码。"]],
  phonics=dict(tip="字母 n 的发音是 /n/", words="name 名字 · new 新的 · nine 九"),
  s5_task="这一步我们要做的：把自我介绍的重点收进小背包！",
  s5_voice="今天我们学会了用英语介绍自己：My name is，I am 多少岁。还学了字母 n 的发音。记住这些，你就能大方地和外国朋友打招呼啦！",
  boss=dict(title="Boss 关：自我介绍大挑战", type="mc",
            q="大 Boss：下面哪句话是「我叫李华，我九岁了」？",
            opts=["My name is Li Hua. I'm nine years old.", "My name is nine. I'm Li Hua.", "I'm Li Hua. My name is nine years old."],
            ok=0, hint="先说名字 My name is Li Hua，再说年龄 I'm nine years old."),
  s6_task="这一步我们要做的：打败自我介绍大 Boss，赢双倍星星！",
  s6_voice="最后的大 Boss 来啦！它想考考你能不能把名字和年龄说对。仔细读一读再选，赢了奖励两颗星！",
  parent=dict(summary="会用 What's your name? 询问，用 My name is / I'm ... years old 介绍名字和年龄。",
              attention="孩子容易把 name 和 number 记混、把 I'm 与 My name 位置弄反；重点看练习第 2 题和 Boss 关。",
              tip="本课约 8 分钟；建议孩子开口跟读每一句，家长可一起角色扮演互相介绍。"),
),

dict(
  id="english-3-002", grade=3, term="上册", unit="Unit 2 My Body",
  file_unit="Unit2-MyBody", title="我的身体", module="vocab", difficulty="基础",
  summary="认识身体部位单词与 This is 句型",
  keywords=["身体", "body", "部位", "This is"],
  prereq=[], fileName="英语-三上-Unit2-MyBody-english-3-002-我的身体.html",
  scene=dict(h2="受伤的小恐龙", text="小恐龙玩滑板摔了一跤，指着自己的腿喊疼。它要用英语告诉医生哪里受伤了，得先知道身体的各个部位怎么说！",
             question="想一想：头、手、脚用英语怎么说？", hint="想不出来也没关系，我们马上学！"),
  s1_task="咱们这一步要做的：帮小恐龙说出身体部位！",
  s1_voice="小恐龙玩滑板摔了一跤，腿疼得直叫。它想用英语告诉医生哪里受伤了，可是还不会说身体部位的单词。今天我们就来帮它认识自己的身体，你准备好了吗？",
  words_title="单词大本营：我的身体", words_intro="点一点卡片，认识我们身体的各个部位，跟读一遍吧！",
  s2_task="这一步我们要做的：认识身体的每个部位，点卡片听发音！",
  s2_voice="我们身上有好多部位：头、头发、眼睛、鼻子、嘴巴、手、腿、脚。点一点卡片，听听它们用英语怎么说，再跟着读一读。",
  words=[dict(e="head", z="头", em="👦"), dict(e="hair", z="头发", em="💇"), dict(e="eye", z="眼睛", em="👀"),
         dict(e="ear", z="耳朵", em="👂"), dict(e="nose", z="鼻子", em="👃"), dict(e="mouth", z="嘴", em="👄"),
         dict(e="hand", z="手", em="✋"), dict(e="arm", z="胳膊", em="💪"), dict(e="leg", z="腿", em="🦵"),
         dict(e="foot", z="脚", em="🦶"), dict(e="body", z="身体", em="🧍")],
  pattern=dict(title="句型魔法：这是我的…", sentence=["This", "is", "my", "nose", "."], zh="这是我的鼻子。",
               desc="This is my ... 这是我的…（一个） ｜ These are my ... 这些是我的…（多个） ｜ I hurt my ... 我弄伤了…"),
  order=dict(zh="帮小恐龙说出「这是我的鼻子」", words=["This", "is", "my", "nose", "."], right=[0, 1, 2, 3, 4],
             hint="先说 This is，再说 my，最后说部位～"),
  s3_task="这一步我们要做的：看 This is 句型怎么用，再自己拼一句！",
  s3_voice="介绍身体部位的时候，我们用 This is my 加上部位的名字。看动画里句子一块块拼出来，然后你来动手，把「这是我的鼻子」拼成英文吧！",
  quiz=[dict(q="「这是我的头」用英语怎么说？", opts=["This is my head.", "This is my hand.", "I hurt my head."], ok=0, hint="头是 head，This is my 表示这是我的"),
        dict(q="眼睛用英语怎么说？", opts=["eye", "ear", "nose"], ok=0, hint="eye 是眼睛，ear 是耳朵"),
        dict(q="I hurt my leg. 的意思是？", opts=["我伤了腿。", "我喜欢腿。", "这是我的腿。"], ok=0, hint="hurt 是受伤、弄伤")],
  s4_task="这一步我们要做的：连闯三道小题，把身体单词用起来！",
  s4_voice="现在轮到你啦！三道小题，考考你对身体部位和 This is 句型记住了没有。答对就能得到星星哦。",
  summary_points=[["身体部位", "head 头 · eye 眼睛 · nose 鼻子 · mouth 嘴 · hand 手 · leg 腿 · foot 脚"],
                  ["这是我的", "This is my ... 这是我的…（单个）"],
                  ["这些是我的", "These are my ... 这些是我的…（多个）"]],
  phonics=dict(tip="字母 h 的发音是 /h/", words="head 头 · hand 手 · help 帮助"),
  s5_task="这一步我们要做的：把身体部位的单词收进小背包！",
  s5_voice="今天我们认识了身体的好多部位，还学会了说 This is my 这是我的。以后不小心受伤，就能用英语告诉别人了！",
  boss=dict(title="Boss 关：身体大挑战", type="mc",
            q="大 Boss：选出正确的句子「这是我的双手。」",
            opts=["These are my hands.", "This is my hand.", "I hurt my hands."],
            ok=0, hint="双手是两个，要用 These are，手也要用复数 hands"),
  s6_task="这一步我们要做的：打败身体大 Boss，赢双倍星星！",
  s6_voice="最后的大 Boss 来啦！它问的是「这是我的双手」。记住：两个以上的部位要用 These are 哦。选对就奖励两颗星！",
  parent=dict(summary="认识 head/eye/nose/mouth/hand/leg/foot 等身体部位，会用 This is my 与 These are my 表达。",
              attention="This is（一个）和 These are（多个）容易混，foot 复数 feet 也要提醒；重点看 Boss 关。",
              tip="本课约 8 分钟；可让孩子边说边指自己的身体部位，加深记忆。"),
),

dict(
  id="english-3-003", grade=3, term="上册", unit="Unit 3 Food",
  file_unit="Unit3-Food", title="食物", module="vocab", difficulty="基础",
  summary="食物单词与 I like / I don't like 表达",
  keywords=["食物", "food", "喜欢", "不喜欢"],
  prereq=[], fileName="英语-三上-Unit3-Food-english-3-003-食物.html",
  scene=dict(h2="饿了的小熊", text="小熊肚子咕咕叫，来到餐厅想点餐。它要用英语说出自己喜欢吃什么，还要有礼貌地表达想要什么。",
             question="想一想：面包、牛奶、果汁用英语怎么说？", hint="跟着小熊一起学点餐吧！"),
  s1_task="咱们这一步要做的：帮小熊用英语点餐！",
  s1_voice="小熊肚子饿得咕咕叫，它来到餐厅，却不会用英语说想吃什么。今天我们来学食物的单词，还要学会说我喜欢和我不喜欢。",
  words_title="单词大本营：食物", words_intro="点一点卡片，认识这些好吃的食物，跟读一遍吧！",
  s2_task="这一步我们要做的：认识食物的单词，点卡片听发音！",
  s2_voice="这一单元我们认识几种好吃的：面包、蛋糕、鸡蛋、米饭、牛奶、果汁、水、茶、水果、汉堡。点一点卡片，听一听，跟着读一读。",
  words=[dict(e="bread", z="面包", em="🍞"), dict(e="cake", z="蛋糕", em="🎂"), dict(e="egg", z="鸡蛋", em="🥚"),
         dict(e="rice", z="米饭", em="🍚"), dict(e="milk", z="牛奶", em="🥛"), dict(e="juice", z="果汁", em="🧃"),
         dict(e="water", z="水", em="💧"), dict(e="tea", z="茶", em="🍵"), dict(e="fruit", z="水果", em="🍎"),
         dict(e="hamburger", z="汉堡", em="🍔")],
  pattern=dict(title="句型魔法：我喜欢…", sentence=["I", "like", "milk", "."], zh="我喜欢牛奶。",
               desc="I like ... 我喜欢… ｜ I don't like ... 我不喜欢… ｜ Would you like some ...? 你想要…吗？ 回答 Yes, please."),
  order=dict(zh="帮小熊说「我不喜欢茶」", words=["I", "don't", "like", "tea", "."], right=[0, 1, 2, 3, 4],
             hint="不喜欢要说 I don't like，don't 就是「不」"),
  s3_task="这一步我们要做的：看 I like 句型怎么用，再拼一句「我不喜欢茶」！",
  s3_voice="说自己喜欢什么，用 I like 加上食物。说不喜欢，就用 I don't like。看句子拼出来，然后轮到你把「我不喜欢茶」排出来。",
  quiz=[dict(q="「我喜欢牛奶」用英语怎么说？", opts=["I like milk.", "I don't like milk.", "Would you like milk?"], ok=0, hint="喜欢用 I like"),
        dict(q="bread 的意思是？", opts=["面包", "蛋糕", "米饭"], ok=0, hint="bread 是面包"),
        dict(q="别人问 Would you like some juice?，你想要，怎么回答？", opts=["Yes, please.", "No, I like.", "Yes, I like juice please."], ok=0, hint="想要就回答 Yes, please.")],
  s4_task="这一步我们要做的：连闯三道小题，把食物单词用起来！",
  s4_voice="现在轮到你啦！三道小题，考考食物单词和 I like 句型。答对就能得到星星哦。",
  summary_points=[["食物单词", "bread 面包 · cake 蛋糕 · milk 牛奶 · juice 果汁 · rice 米饭"],
                  ["喜欢与不喜欢", "I like ... 我喜欢… ｜ I don't like ... 我不喜欢…"],
                  ["礼貌问答", "Would you like ...? 回答 Yes, please. / No, thank you."]],
  phonics=dict(tip="字母 f 的发音是 /f/", words="food 食物 · fish 鱼 · four 四"),
  s5_task="这一步我们要做的：把食物的单词收进小背包！",
  s5_voice="今天我们学了食物的单词，还学会了说我喜欢什么、不喜欢什么。以后去餐厅点餐，你也能用英语啦！",
  boss=dict(title="Boss 关：点餐大挑战", type="mc",
            q="大 Boss：你想喝果汁，怎么用英语有礼貌地说？",
            opts=["Would you like some juice?", "I don't like juice.", "May I have some juice, please?"],
            ok=2, hint="请求别人给东西，用 May I have ... please? 最有礼貌"),
  s6_task="这一步我们要做的：打败点餐大 Boss，赢双倍星星！",
  s6_voice="最后的大 Boss 来啦！它想知道你会不会礼貌地请求。注意 May I have ... please? 是最礼貌的说法哦。选对奖励两颗星！",
  parent=dict(summary="认识食物单词，会用 I like / I don't like 表达喜好，会用 Would you like 与 May I have 礼貌问答。",
              attention="I don't 的否定容易漏；礼貌请求 May I have ... please? 是重点，见 Boss 关。",
              tip="本课约 8 分钟；可在家吃饭时用英语问孩子 Do you like ...? 强化表达。"),
),

dict(
  id="english-3-004", grade=3, term="上册", unit="Unit 4 Pets",
  file_unit="Unit4-Pets", title="宠物", module="vocab", difficulty="基础",
  summary="宠物单词与 Do you have 询问表达",
  keywords=["宠物", "pets", "动物", "Do you have"],
  prereq=[], fileName="英语-三上-Unit4-Pets-english-3-004-宠物.html",
  scene=dict(h2="宠物店之旅", text="周末，Binbin 去宠物店玩，店里的小动物们可爱极了！他想知道小伙伴有没有养小动物。",
             question="想一想：你会用英语问「你养狗吗？」吗？", hint="学完这课，你就能和小伙伴聊宠物啦！"),
  s1_task="咱们这一步要做的：学会用英语聊宠物！",
  s1_voice="周末，Binbin 去宠物店，看到好多可爱的小动物。他想问问小伙伴有没有养宠物，我们帮他学会这些单词和问句吧。",
  words_title="单词大本营：宠物", words_intro="点一点卡片，认识这些小动物，跟读一遍吧！",
  s2_task="这一步我们要做的：认识小动物的单词，点卡片听发音！",
  s2_voice="宠物店里住着猫、狗、小鸟、小鱼、小兔，还有猴子、老虎和大熊猫。点一点卡片，听听它们的英文名字，跟着读一读。",
  words=[dict(e="cat", z="猫", em="🐱"), dict(e="dog", z="狗", em="🐶"), dict(e="bird", z="鸟", em="🐦"),
         dict(e="fish", z="鱼", em="🐟"), dict(e="rabbit", z="兔子", em="🐰"), dict(e="monkey", z="猴子", em="🐵"),
         dict(e="tiger", z="老虎", em="🐯"), dict(e="panda", z="熊猫", em="🐼")],
  pattern=dict(title="句型魔法：你有…吗？", sentence=["I", "have", "a", "dog", "."], zh="我有一只狗。",
               desc="Do you have ...? 你有…吗？ 回答 Yes, I do. / No, I don't. ｜ I have ... 我有…"),
  order=dict(zh="帮 Binbin 问「你有一只猫吗？」", words=["Do", "you", "have", "a", "cat", "?"], right=[0, 1, 2, 3, 4, 5],
             hint="问句开头是 Do you，别忘了后面的问号"),
  s3_task="这一步我们要做的：看 Do you have 怎么用，再拼一个问句！",
  s3_voice="想知道别人有没有养宠物，用 Do you have 加上小动物。看句子拼出来，然后你来把问句「你有一只猫吗」排出来。",
  quiz=[dict(q="「你有一只猫吗？」用英语怎么说？", opts=["Do you have a cat?", "I have a cat.", "You have a cat?"], ok=0, hint="问别人有没有用 Do you have ...?"),
        dict(q="rabbit 是？", opts=["兔子", "老虎", "猴子"], ok=0, hint="rabbit 是兔子"),
        dict(q="Do you have a dog? 的否定回答是？", opts=["No, I don't.", "Yes, I do.", "No, I do."], ok=0, hint="没有就回答 No, I don't.")],
  s4_task="这一步我们要做的：连闯三道小题，把宠物单词用起来！",
  s4_voice="现在轮到你啦！三道小题，考考小动物的单词和 Do you have 问句。答对就能得到星星哦。",
  summary_points=[["宠物单词", "cat 猫 · dog 狗 · bird 鸟 · fish 鱼 · rabbit 兔子 · panda 熊猫"],
                  ["询问拥有", "Do you have ...? 你有…吗？ 回答 Yes, I do. / No, I don't."],
                  ["我有…", "I have a ... 我有…"]],
  phonics=dict(tip="字母 p 的发音是 /p/", words="pet 宠物 · pig 猪 · pen 钢笔"),
  s5_task="这一步我们要做的：把宠物的单词收进小背包！",
  s5_voice="今天我们认识了可爱的小动物，还学会了问别人有没有养宠物。Do you have a cat？你有猫吗？",
  boss=dict(title="Boss 关：宠物大挑战", type="mc",
            q="大 Boss：妈妈问你「Do you have a rabbit?」，你没有，怎么回答？",
            opts=["No, I don't.", "Yes, I have.", "No, I have a rabbit."],
            ok=0, hint="没有就回答 No, I don't."),
  s6_task="这一步我们要做的：打败宠物大 Boss，赢双倍星星！",
  s6_voice="最后的大 Boss 来啦！妈妈问你有没有兔子，你没有。记住：没有就回答 No, I don't。选对奖励两颗星！",
  parent=dict(summary="认识宠物单词，会用 Do you have ...? 询问并用 Yes, I do. / No, I don't. 回答。",
              attention="肯定回答易说成 Yes, I have；应记 Yes, I do. / No, I don't. 配对。",
              tip="本课约 8 分钟；可问问孩子 Do you have a pet? 用英语聊一聊家里的宠物。"),
),

dict(
  id="english-3-005", grade=3, term="上册", unit="Unit 5 Clothes",
  file_unit="Unit5-Clothes", title="衣服", module="vocab", difficulty="提高",
  summary="衣服单词与 What colour 问颜色",
  keywords=["衣服", "clothes", "颜色", "colour"],
  prereq=[], fileName="英语-三上-Unit5-Clothes-english-3-005-衣服.html",
  scene=dict(h2="挑衣服的小淘气", text="明天要拍照啦！小淘气在衣柜前挑衣服，红的、蓝的、黄的……它要用英语说出每件衣服和颜色。",
             question="想一想：T恤、短裙、帽子用英语怎么说？", hint="跟着小淘气一起挑衣服学单词！"),
  s1_task="咱们这一步要做的：帮小淘气说出衣服和颜色！",
  s1_voice="小淘气明天要拍照，正在衣柜前挑衣服。它想知道每件衣服叫什么、是什么颜色。今天我们来学衣服的单词和问颜色的句型。",
  words_title="单词大本营：衣服", words_intro="点一点卡片，认识这些衣服，跟读一遍吧！",
  s2_task="这一步我们要做的：认识衣服的单词，点卡片听发音！",
  s2_voice="衣柜里有 T 恤、衬衫、短裙、连衣裙、外套、毛衣、牛仔裤、袜子、鞋子，还有帽子。点一点卡片，听一听，跟着读一读。",
  words=[dict(e="T-shirt", z="T恤", em="👕"), dict(e="shirt", z="衬衫", em="👔"), dict(e="skirt", z="短裙", em="👗"),
         dict(e="dress", z="连衣裙", em="👗"), dict(e="coat", z="外套", em="🧥"), dict(e="sweater", z="毛衣", em="🧶"),
         dict(e="jeans", z="牛仔裤", em="👖"), dict(e="socks", z="袜子", em="🧦"), dict(e="shoes", z="鞋", em="👟"),
         dict(e="cap", z="帽子", em="🧢")],
  pattern=dict(title="句型魔法：什么颜色？", sentence=["I", "like", "the", "red", "dress", "."], zh="我喜欢这条红色的连衣裙。",
               desc="What colour is ...? 它是什么颜色？ 回答 It's blue. 它是蓝色的。 ｜ I like the ... 我喜欢…"),
  order=dict(zh="帮小淘气问「你的衬衫是什么颜色？」", words=["What", "colour", "is", "your", "shirt", "?"], right=[0, 1, 2, 3, 4, 5],
             hint="问颜色用 What colour is ...?"),
  s3_task="这一步我们要做的：看 What colour 怎么用，再拼一个问颜色的句子！",
  s3_voice="想知道一件衣服是什么颜色，用 What colour is 加上衣服。看句子拼出来，然后你来把「你的衬衫是什么颜色」排出来。",
  quiz=[dict(q="「你的衬衫是什么颜色？」用英语怎么说？", opts=["What colour is your shirt?", "What is your shirt?", "Is your shirt blue?"], ok=0, hint="问颜色用 What colour is ...?"),
        dict(q="socks 是？", opts=["袜子", "鞋子", "裤子"], ok=0, hint="socks 是袜子，shoes 是鞋"),
        dict(q="It's blue. 的意思是？", opts=["它是蓝色的。", "它是黑色的。", "它是红色的。"], ok=0, hint="blue 是蓝色")],
  s4_task="这一步我们要做的：连闯三道小题，把衣服单词用起来！",
  s4_voice="现在轮到你啦！三道小题，考考衣服的单词和问颜色。答对就能得到星星哦。",
  summary_points=[["衣服单词", "T-shirt T恤 · skirt 短裙 · coat 外套 · socks 袜子 · shoes 鞋 · cap 帽子"],
                  ["问颜色", "What colour is ...? 它是什么颜色？ 回答 It's ..."],
                  ["我喜欢…", "I like the ... dress. 我喜欢…的连衣裙"]],
  phonics=dict(tip="字母 s 的发音是 /s/", words="socks 袜子 · shirt 衬衫 · skirt 短裙"),
  s5_task="这一步我们要做的：把衣服的单词收进小背包！",
  s5_voice="今天我们认识了各种衣服，还学会了问颜色 What colour。以后挑衣服的时候，你也能用英语啦！",
  boss=dict(title="Boss 关：挑衣服大挑战", type="mc",
            q="大 Boss：你想问「你喜欢这件黄色的 T 恤吗？」，怎么问？",
            opts=["Do you like the yellow T-shirt?", "What colour is the T-shirt?", "I like the yellow T-shirt."],
            ok=0, hint="问别人喜不喜欢，用 Do you like ...?"),
  s6_task="这一步我们要做的：打败挑衣服大 Boss，赢双倍星星！",
  s6_voice="最后的大 Boss 来啦！它想问你喜不喜欢黄色的 T 恤。记住问喜不喜欢用 Do you like。选对奖励两颗星！",
  parent=dict(summary="认识衣服单词，会用 What colour is ...? 问颜色、Do you like ...? 问喜好。",
              attention="颜色形容词放名词前（the red dress）；问喜好用 Do you like 而非 What colour。",
              tip="本课约 8 分钟；可让孩子指着衣服用 What colour 问家长。"),
),

dict(
  id="english-3-006", grade=3, term="上册", unit="Unit 6 Birthdays",
  file_unit="Unit6-Birthdays", title="生日", module="vocab", difficulty="基础",
  summary="生日祝福与 When is your birthday 表达",
  keywords=["生日", "birthday", "祝福", "月份"],
  prereq=[], fileName="英语-三上-Unit6-Birthdays-english-3-006-生日.html",
  scene=dict(h2="生日的惊喜", text="今天是 Lucky 的生日！朋友们准备了蛋糕和礼物。大家要唱生日歌，还要问他的生日是哪个月。",
             question="想一想：你会用英语说「生日快乐」吗？", hint="学完这课，你也能给别人送生日祝福！"),
  s1_task="咱们这一步要做的：学会用英语送生日祝福！",
  s1_voice="今天是小狗 Lucky 的生日，朋友们准备了蛋糕和礼物。我们一起来学会说生日快乐，还会问别人的生日是什么时候。",
  words_title="单词大本营：生日", words_intro="点一点卡片，认识这些生日相关的单词，跟读一遍吧！",
  s2_task="这一步我们要做的：认识生日的单词，点卡片听发音！",
  s2_voice="生日这一天有蛋糕、礼物、聚会和卡片。点一点卡片，听听它们用英语怎么说，跟着读一读。",
  words=[dict(e="birthday", z="生日", em="🎂"), dict(e="cake", z="蛋糕", em="🎂"), dict(e="present", z="礼物", em="🎁"),
         dict(e="party", z="聚会", em="🎉"), dict(e="card", z="卡片", em="💌"), dict(e="month", z="月份", em="📅"),
         dict(e="happy", z="快乐的", em="😊"), dict(e="candle", z="蜡烛", em="🕯️")],
  pattern=dict(title="句型魔法：生日快乐！", sentence=["Happy", "birthday", "to", "you", "!"], zh="祝你生日快乐！",
               desc="Happy birthday! 生日快乐！ ｜ When is your birthday? 你的生日是什么时候？ ｜ My birthday is in May. 我的生日在五月。"),
  order=dict(zh="帮大家问「你的生日是什么时候？」", words=["When", "is", "your", "birthday", "?"], right=[0, 1, 2, 3, 4],
             hint="问生日用 When is your birthday?"),
  s3_task="这一步我们要做的：看生日祝福怎么用，再拼一个问句！",
  s3_voice="送祝福要说 Happy birthday，问生日是什么时候用 When is your birthday。看句子拼出来，然后你来拼问句。",
  quiz=[dict(q="「生日快乐」用英语怎么说？", opts=["Happy birthday!", "When is your birthday?", "My birthday is in May."], ok=0, hint="祝福用 Happy birthday!"),
        dict(q="present 的意思是？", opts=["礼物", "蛋糕", "卡片"], ok=0, hint="present 是礼物"),
        dict(q="「我的生日在五月」怎么说？", opts=["My birthday is in May.", "My birthday is May.", "I'm in May."], ok=0, hint="生日在几月用 in + 月份")],
  s4_task="这一步我们要做的：连闯三道小题，把生日单词用起来！",
  s4_voice="现在轮到你啦！三道小题，考考生日的单词和祝福语。答对就能得到星星哦。",
  summary_points=[["生日祝福", "Happy birthday! 生日快乐！"],
                  ["问生日", "When is your birthday? 你的生日什么时候？"],
                  ["回答", "My birthday is in ... 我的生日在…（月份）"]],
  phonics=dict(tip="字母 b 的发音是 /b/", words="birthday 生日 · book 书 · ball 球"),
  s5_task="这一步我们要做的：把生日的祝福收进小背包！",
  s5_voice="今天我们学会了说生日快乐，还会问别人的生日。下次朋友过生日，你就能用英语祝福他啦！",
  boss=dict(title="Boss 关：生日大挑战", type="mc",
            q="大 Boss：朋友生日，你想送他礼物并说「这是给你的礼物」，怎么说？",
            opts=["Here's a present for you.", "Here's a cake for you.", "Happy birthday for you."],
            ok=0, hint="送礼物说 Here's a present for you."),
  s6_task="这一步我们要做的：打败生日大 Boss，赢双倍星星！",
  s6_voice="最后的大 Boss 来啦！送礼物的时候要说 Here's a present for you，这是给你的礼物。选对奖励两颗星！",
  parent=dict(summary="会说 Happy birthday!，会用 When is your birthday? 问生日并用 in + 月份回答。",
              attention="月份前要加 in（in May）；Here's = Here is，送礼物用语见 Boss 关。",
              tip="本课约 8 分钟；可把全家人的生日用英语各问一遍。"),
),

# ============================ 三年级下册 ============================
dict(
  id="english-3-011", grade=3, term="下册", unit="Unit 1 School Subjects",
  file_unit="Unit1-SchoolSubjects", title="学校课程", module="vocab", difficulty="基础",
  summary="科目单词与 What's your favourite subject 表达",
  keywords=["科目", "school subjects", "课程", "favourite"],
  prereq=[], fileName="英语-三下-Unit1-SchoolSubjects-english-3-011-学校课程.html",
  scene=dict(h2="课表上的秘密", text="新学期的课表发下来啦！语文、数学、英语、体育……Binbin 最喜欢英语课，他要用英语说说自己最喜欢的科目。",
             question="想一想：语文、英语、体育用英语怎么说？", hint="和课表交朋友，一起学起来！"),
  s1_task="咱们这一步要做的：学会用英语说喜欢的科目！",
  s1_voice="新学期的课表发下来了，上面有好多科目。Binbin 最喜欢英语课，他想知道小伙伴最喜欢什么。今天我们学会科目的单词和问句。",
  words_title="单词大本营：学校课程", words_intro="点一点卡片，认识这些科目，跟读一遍吧！",
  s2_task="这一步我们要做的：认识科目的单词，点卡片听发音！",
  s2_voice="课表上有语文、英语、数学、科学、体育、音乐、美术，还有计算机课。点一点卡片，听听它们用英语怎么说，跟着读一读。",
  words=[dict(e="Chinese", z="语文", em="📕"), dict(e="English", z="英语", em="📘"), dict(e="maths", z="数学", em="📐"),
         dict(e="science", z="科学", em="🔬"), dict(e="PE", z="体育", em="⚽"), dict(e="music", z="音乐", em="🎵"),
         dict(e="art", z="美术", em="🎨"), dict(e="computer class", z="计算机课", em="💻")],
  pattern=dict(title="句型魔法：我最喜欢…", sentence=["I", "like", "English", "best", "."], zh="我最喜欢英语。",
               desc="What's your favourite subject? 你最喜欢什么科目？ ｜ I like ... best. 我最喜欢… ｜ Do you like ...? 你喜欢…吗？"),
  order=dict(zh="帮 Binbin 说「我最喜欢英语」", words=["I", "like", "English", "best", "."], right=[0, 1, 2, 3, 4],
             hint="最喜欢用 like ... best，best 放最后"),
  s3_task="这一步我们要做的：看句型怎么用，再拼一句「我最喜欢英语」！",
  s3_voice="说自己最喜欢什么科目，用 I like 加上科目，最后加 best 表示最。看句子拼出来，然后你来动手拼一拼。",
  quiz=[dict(q="「你最喜欢的科目是什么？」用英语怎么说？", opts=["What's your favourite subject?", "What's your name?", "What do you like?"], ok=0, hint="问最喜欢的科目用 favourite subject"),
        dict(q="PE 是？", opts=["体育", "美术", "音乐"], ok=0, hint="PE 是体育"),
        dict(q="I like maths best. 的意思是？", opts=["我最喜欢数学。", "我讨厌数学。", "我在学数学。"], ok=0, hint="best 是最的意思")],
  s4_task="这一步我们要做的：连闯三道小题，把科目单词用起来！",
  s4_voice="现在轮到你啦！三道小题，考考科目的单词和 favourite 句型。答对就能得到星星哦。",
  summary_points=[["科目单词", "Chinese 语文 · English 英语 · maths 数学 · PE 体育 · music 音乐"],
                  ["询问喜好", "What's your favourite subject? 你最喜欢什么科目？"],
                  ["回答", "I like ... best. 我最喜欢…"]],
  phonics=dict(tip="字母 a：在 name、cake 里读长音 /eɪ/，在 cat、bag 里读短音 /æ/", words="name · cake ｜ cat · bag"),
  s5_task="这一步我们要做的：把科目的单词收进小背包！",
  s5_voice="今天我们认识了课表上的科目，还学会了说我最喜欢什么。下次别人问你最喜欢什么课，你就能用英语回答啦！",
  boss=dict(title="Boss 关：课程大挑战", type="mc",
            q="大 Boss：弟弟问你「Do you like music?」，你喜欢，怎么回答？",
            opts=["Yes, I do.", "No, I don't.", "Yes, I like best."],
            ok=0, hint="喜欢就回答 Yes, I do."),
  s6_task="这一步我们要做的：打败课程大 Boss，赢双倍星星！",
  s6_voice="最后的大 Boss 来啦！别人问你喜不喜欢音乐，喜欢就回答 Yes, I do。选对奖励两颗星！",
  parent=dict(summary="认识科目单词，会用 What's your favourite subject? 与 I like ... best 表达喜好。",
              attention="favourite 意思是「最喜欢的」；喜欢与否用 Yes, I do / No, I don't 回答。",
              tip="本课约 8 分钟；可让孩子用英语介绍今天上了什么课。"),
),

dict(
  id="english-3-012", grade=3, term="下册", unit="Unit 2 My School",
  file_unit="Unit2-MySchool", title="我的学校", module="vocab", difficulty="基础",
  summary="学校地点与 Where is 问路表达",
  keywords=["学校", "school", "地点", "Where is"],
  prereq=[], fileName="英语-三下-Unit2-MySchool-english-3-012-我的学校.html",
  scene=dict(h2="校园小导游", text="新同学来参观学校啦！Binbin 当小导游，要带大家看看教室、图书馆、操场都在哪里。",
             question="想一想：教室、图书馆用英语怎么说？", hint="跟着小导游逛校园！"),
  s1_task="咱们这一步要做的：学会用英语介绍学校的地方！",
  s1_voice="新同学来参观学校，Binbin 当小导游。他想用英语介绍教室、图书馆、操场都在哪里。今天我们学会这些地点和问句。",
  words_title="单词大本营：我的学校", words_intro="点一点卡片，认识学校里的地方，跟读一遍吧！",
  s2_task="这一步我们要做的：认识学校的地点，点卡片听发音！",
  s2_voice="学校里有教室、图书馆、洗手间、操场，还有办公室和大厅。楼层有第一层、第二层、第三层。点一点卡片，跟着读一读。",
  words=[dict(e="classroom", z="教室", em="🏫"), dict(e="library", z="图书馆", em="📚"), dict(e="toilet", z="洗手间", em="🚻"),
         dict(e="playground", z="操场", em="⚽"), dict(e="office", z="办公室", em="🏢"), dict(e="hall", z="大厅", em="🏛️"),
         dict(e="floor", z="楼层", em="🏢"), dict(e="first", z="第一的", em="1️⃣"), dict(e="second", z="第二的", em="2️⃣"),
         dict(e="third", z="第三的", em="3️⃣")],
  pattern=dict(title="句型魔法：…在哪里？", sentence=["The", "library", "is", "on", "the", "second", "floor", "."], zh="图书馆在二楼。",
               desc="Where is ...? …在哪里？ ｜ It's on the ... floor. 它在…楼。 ｜ This is our classroom. 这是我们的教室。"),
  order=dict(zh="帮小导游问「图书馆在哪里？」", words=["Where", "is", "the", "library", "?"], right=[0, 1, 2, 3, 4],
             hint="问在哪里用 Where is ...?"),
  s3_task="这一步我们要做的：看 Where is 怎么用，再拼一个问句！",
  s3_voice="想知道一个地方在哪里，用 Where is 加上地方。回答可以说在几楼。看句子拼出来，然后你来拼问句。",
  quiz=[dict(q="「图书馆在哪里？」用英语怎么说？", opts=["Where is the library?", "What is the library?", "This is the library."], ok=0, hint="问在哪里用 Where is ...?"),
        dict(q="playground 是？", opts=["操场", "教室", "图书馆"], ok=0, hint="playground 是操场"),
        dict(q="It's on the second floor. 的意思是？", opts=["它在二楼。", "它在一楼。", "它在三楼。"], ok=0, hint="second floor 是二楼")],
  s4_task="这一步我们要做的：连闯三道小题，把学校地点用起来！",
  s4_voice="现在轮到你啦！三道小题，考考学校的地点单词。答对就能得到星星哦。",
  summary_points=[["学校地点", "classroom 教室 · library 图书馆 · playground 操场 · office 办公室"],
                  ["问地点", "Where is ...? 在哪？"],
                  ["楼层表达", "on the first / second / third floor 在一 / 二 / 三楼"]],
  phonics=dict(tip="字母 l 的发音是 /l/", words="library 图书馆 · look 看 · like 喜欢"),
  s5_task="这一步我们要做的：把学校地点的单词收进小背包！",
  s5_voice="今天我们认识了学校里的地方，还学会了问在哪里。以后有同学问路，你也能用英语帮他啦！",
  boss=dict(title="Boss 关：校园大挑战", type="mc",
            q="大 Boss：你想告诉别人「教室在一楼」，怎么说？",
            opts=["The classroom is on the first floor.", "The classroom is on the second floor.", "Where is the classroom?"],
            ok=0, hint="一楼是 the first floor"),
  s6_task="这一步我们要做的：打败校园大 Boss，赢双倍星星！",
  s6_voice="最后的大 Boss 来啦！它想知道教室在哪一层。记住一楼是 first floor。选对奖励两颗星！",
  parent=dict(summary="认识学校地点，会用 Where is ...? 问位置并用 on the ... floor 回答。",
              attention="楼层序数 first/second/third 是重点；Where is 与 What is 不要混。",
              tip="本课约 8 分钟；可在校园里指着建筑用英语问 Where is ...?。"),
),

dict(
  id="english-3-013", grade=3, term="下册", unit="Unit 3 After School Activities",
  file_unit="Unit3-AfterSchoolActivities", title="放学后活动", module="vocab", difficulty="基础",
  summary="课后活动与 What do you do after school 表达",
  keywords=["放学后", "after school", "活动", "做什么"],
  prereq=[], fileName="英语-三下-Unit3-AfterSchoolActivities-english-3-013-放学后活动.html",
  scene=dict(h2="放学后的快乐", text="叮铃铃，放学啦！Binbin 和小伙伴们在操场上踢球、画画、下棋，玩得可开心了。",
             question="想一想：你会用英语说「踢足球」「画画」吗？", hint="放学后的活动，学起来超有用！"),
  s1_task="咱们这一步要做的：学会用英语说放学后的活动！",
  s1_voice="放学啦，Binbin 和小伙伴们在操场上玩得真开心，有的踢球、有的画画、有的下棋。今天我们学会这些活动怎么说。",
  words_title="单词大本营：放学后活动", words_intro="点一点卡片，认识这些活动，跟读一遍吧！",
  s2_task="这一步我们要做的：认识活动的单词，点卡片听发音！",
  s2_voice="放学后可以做什么呢？可以做运动、画画、下棋、跳舞、唱歌、读书，还可以踢足球。点一点卡片，跟着读一读。",
  words=[dict(e="after school", z="放学后", em="⏰"), dict(e="play sports", z="做运动", em="⚽"),
         dict(e="draw pictures", z="画画", em="🎨"), dict(e="play chess", z="下棋", em="♟️"),
         dict(e="dance", z="跳舞", em="💃"), dict(e="sing songs", z="唱歌", em="🎤"),
         dict(e="read books", z="读书", em="📖"), dict(e="play football", z="踢足球", em="⚽")],
  pattern=dict(title="句型魔法：你放学后做什么？", sentence=["I", "play", "sports", "after", "school", "."], zh="我放学后做运动。",
               desc="What do you do after school? 你放学后做什么？ ｜ I ... after school. 我放学后… ｜ Do you like ...? 你喜欢…吗？"),
  order=dict(zh="帮 Binbin 问「你放学后做什么？」", words=["What", "do", "you", "do", "after", "school", "?"], right=[0, 1, 2, 3, 4, 5, 6],
             hint="问放学后做什么用 What do you do after school?"),
  s3_task="这一步我们要做的：看问句怎么用，再拼一个问句！",
  s3_voice="想知道别人放学后做什么，用 What do you do after school。看句子拼出来，然后你来拼问句。",
  quiz=[dict(q="「我放学后画画」用英语怎么说？", opts=["I draw pictures after school.", "I play chess after school.", "I read books after school."], ok=0, hint="画画是 draw pictures"),
        dict(q="play chess 是？", opts=["下棋", "踢球", "画画"], ok=0, hint="chess 是国际象棋"),
        dict(q="What do you do after school? 是问？", opts=["你放学后做什么？", "你几点放学？", "你喜欢上学吗？"], ok=0, hint="after school 是放学后")],
  s4_task="这一步我们要做的：连闯三道小题，把活动单词用起来！",
  s4_voice="现在轮到你啦！三道小题，考考活动的单词和问句。答对就能得到星星哦。",
  summary_points=[["活动单词", "play sports 做运动 · draw pictures 画画 · play chess 下棋 · dance 跳舞"],
                  ["询问活动", "What do you do after school? 你放学后做什么？"],
                  ["回答", "I ... after school. 我放学后…"]],
  phonics=dict(tip="字母组合 sh 发 /ʃ/，像「嘘」", words="fish 鱼 · sheep 羊 · shoes 鞋"),
  s5_task="这一步我们要做的：把活动的单词收进小背包！",
  s5_voice="今天我们学会了放学后的各种活动，还会问别人放学后做什么。以后就能和小伙伴用英语聊课后的安排啦！",
  boss=dict(title="Boss 关：活动大挑战", type="mc",
            q="大 Boss：你想问小伙伴「你放学后踢足球吗？」，怎么说？",
            opts=["Do you play football after school?", "What do you do after school?", "I play football after school."],
            ok=0, hint="问是不是做某事，用 Do you ...?"),
  s6_task="这一步我们要做的：打败活动大 Boss，赢双倍星星！",
  s6_voice="最后的大 Boss 来啦！问别人放学后踢不踢足球，用 Do you play football。选对奖励两颗星！",
  parent=dict(summary="认识课后活动，会用 What do you do after school? 询问并用 I ... 回答。",
              attention="do 的两个用法（What do you do?）孩子容易晕；Do you ...? 一般疑问句要重点练。",
              tip="本课约 8 分钟；可让孩子用英语说说自己放学后的安排。"),
),

dict(
  id="english-3-014", grade=3, term="下册", unit="Unit 4 My Family",
  file_unit="Unit4-MyFamily", title="我的家庭", module="vocab", difficulty="基础",
  summary="家庭成员与 This is / Who is 表达",
  keywords=["家庭", "family", "家人", "Who is"],
  prereq=[], fileName="英语-三下-Unit4-MyFamily-english-3-014-我的家庭.html",
  scene=dict(h2="全家福", text="Binbin 带来一张全家福，上面有爸爸、妈妈、爷爷奶奶，还有可爱的妹妹。他要向大家介绍自己的家人。",
             question="想一想：爸爸、妈妈、爷爷用英语怎么说？", hint="学会介绍家人，你也能晒出全家福！"),
  s1_task="咱们这一步要做的：学会用英语介绍家人！",
  s1_voice="Binbin 带来一张全家福，想介绍自己的家人。有爸爸、妈妈、爷爷奶奶，还有妹妹。今天我们学会家人的单词，还会介绍他们。",
  words_title="单词大本营：我的家庭", words_intro="点一点卡片，认识这些家人，跟读一遍吧！",
  s2_task="这一步我们要做的：认识家人的单词，点卡片听发音！",
  s2_voice="家人有爸爸、妈妈、兄弟、姐妹，还有爷爷、奶奶、叔叔、阿姨和表兄妹。点一点卡片，听听它们的英文名字，跟着读一读。",
  words=[dict(e="family", z="家庭", em="👨‍👩‍👧"), dict(e="father", z="爸爸", em="👨"), dict(e="mother", z="妈妈", em="👩"),
         dict(e="brother", z="兄弟", em="👦"), dict(e="sister", z="姐妹", em="👧"), dict(e="grandpa", z="爷爷", em="👴"),
         dict(e="grandma", z="奶奶", em="👵"), dict(e="uncle", z="叔叔", em="👨"), dict(e="aunt", z="阿姨", em="👩"),
         dict(e="cousin", z="表兄妹", em="🧒")],
  pattern=dict(title="句型魔法：这是我的…", sentence=["This", "is", "my", "father", "."], zh="这是我的爸爸。",
               desc="This is my ... 这是我的… ｜ Who is ...? …是谁？ ｜ He's / She's ... 他 / 她是…"),
  order=dict(zh="帮 Binbin 介绍「这是我的家庭」", words=["This", "is", "my", "family", "."], right=[0, 1, 2, 3, 4],
             hint="介绍家人用 This is my ..."),
  s3_task="这一步我们要做的：看 This is 怎么用，再拼一句介绍的话！",
  s3_voice="介绍家人用 This is my 加上家人。想知道照片里的人是谁，用 Who is。看句子拼出来，然后你来拼一句。",
  quiz=[dict(q="「这是我的妈妈」用英语怎么说？", opts=["This is my mother.", "This is my father.", "She is my mother."], ok=0, hint="妈妈是 mother，介绍用 This is my"),
        dict(q="grandpa 是？", opts=["爷爷", "奶奶", "叔叔"], ok=0, hint="grandpa 是爷爷，grandma 是奶奶"),
        dict(q="Who is she? 的回答是？", opts=["She's my grandma.", "He's my grandpa.", "She is grandpa."], ok=0, hint="女生用 She's，男生用 He's")],
  s4_task="这一步我们要做的：连闯三道小题，把家人单词用起来！",
  s4_voice="现在轮到你啦！三道小题，考考家人的单词和介绍句型。答对就能得到星星哦。",
  summary_points=[["家人单词", "father 爸爸 · mother 妈妈 · brother 兄弟 · sister 姐妹 · grandpa 爷爷 · grandma 奶奶"],
                  ["介绍家人", "This is my ... 这是我的…"],
                  ["询问是谁", "Who is ...? 他是谁？ 回答 He's / She's ..."]],
  phonics=dict(tip="字母组合 th 发 /θ/，舌尖轻轻放在牙齿间", words="three 三 · thank 谢谢 · mouth 嘴"),
  s5_task="这一步我们要做的：把家人的单词收进小背包！",
  s5_voice="今天我们认识了家人，还学会了用 This is my 介绍他们。下次拿出全家福，你也能用英语介绍啦！",
  boss=dict(title="Boss 关：家人大挑战", type="mc",
            q="大 Boss：照片里有个不认识的叔叔，你想问「他是谁？」，怎么说？",
            opts=["Who is he?", "Who is she?", "What is he?"],
            ok=0, hint="问男生用 Who is he?"),
  s6_task="这一步我们要做的：打败家人大 Boss，赢双倍星星！",
  s6_voice="最后的大 Boss 来啦！照片里是位叔叔，是男生，要问 Who is he。选对奖励两颗星！",
  parent=dict(summary="认识家庭成员，会用 This is my ... 介绍、Who is ...? 询问。",
              attention="he（他）与 she（她）易混，问叔叔用 Who is he?；重点看 Boss 关。",
              tip="本课约 8 分钟；可翻出全家福让孩子逐个用英语介绍。"),
),

dict(
  id="english-3-015", grade=3, term="下册", unit="Unit 5 Family Activities",
  file_unit="Unit5-FamilyActivities", title="家庭活动", module="vocab", difficulty="提高",
  summary="家庭活动与 We ... together 表达",
  keywords=["家庭活动", "family activities", "一起", "together"],
  prereq=[], fileName="英语-三下-Unit5-FamilyActivities-english-3-015-家庭活动.html",
  scene=dict(h2="温馨的周末", text="周末到了，Binbin 一家人的活动可多啦：爸爸去钓鱼，妈妈去购物，大家一起看电视、做饭……",
             question="想一想：你会用英语说「钓鱼」「看电视」吗？", hint="看看一家人周末都做什么！"),
  s1_task="咱们这一步要做的：学会用英语说和家人做的事！",
  s1_voice="周末，Binbin 一家人各有各的活动：爸爸钓鱼、妈妈购物，大家一起看电视、做饭。今天我们学会这些家庭活动怎么说。",
  words_title="单词大本营：家庭活动", words_intro="点一点卡片，认识这些家庭活动，跟读一遍吧！",
  s2_task="这一步我们要做的：认识家庭活动的单词，点卡片听发音！",
  s2_voice="一家人可以一起钓鱼、购物、看电视、做饭，还能打扫房间、拍照、拜访朋友。点一点卡片，跟着读一读。",
  words=[dict(e="go fishing", z="钓鱼", em="🎣"), dict(e="go shopping", z="购物", em="🛍️"), dict(e="watch TV", z="看电视", em="📺"),
         dict(e="cook", z="做饭", em="🍳"), dict(e="clean the room", z="打扫房间", em="🧹"), dict(e="take photos", z="拍照", em="📷"),
         dict(e="visit friends", z="拜访朋友", em="👋"), dict(e="together", z="一起", em="🤝")],
  pattern=dict(title="句型魔法：我们一起…", sentence=["We", "watch", "TV", "together", "."], zh="我们一起看电视。",
               desc="What do you do with your family? 你和家人做什么？ ｜ We ... together. 我们一起… ｜ My father likes cooking. 我爸爸喜欢做饭。"),
  order=dict(zh="帮 Binbin 说「我们一起看电视」", words=["We", "watch", "TV", "together", "."], right=[0, 1, 2, 3, 4],
             hint="一起做用 together，放在句尾"),
  s3_task="这一步我们要做的：看 We ... together 怎么用，再拼一句！",
  s3_voice="和家人一起做事，用 We 加上动作，最后加 together 表示一起。看句子拼出来，然后你来拼一句。",
  quiz=[dict(q="「我们一起做饭」用英语怎么说？", opts=["We cook together.", "We go fishing together.", "I cook together."], ok=0, hint="一起做饭用 We cook together"),
        dict(q="go fishing 是？", opts=["钓鱼", "购物", "拍照"], ok=0, hint="fishing 是钓鱼"),
        dict(q="take photos 的意思是？", opts=["拍照", "做饭", "看电视"], ok=0, hint="take photos 是拍照")],
  s4_task="这一步我们要做的：连闯三道小题，把家庭活动用起来！",
  s4_voice="现在轮到你啦！三道小题，考考家庭活动的单词。答对就能得到星星哦。",
  summary_points=[["家庭活动", "go fishing 钓鱼 · go shopping 购物 · watch TV 看电视 · cook 做饭"],
                  ["一起做", "We ... together. 我们一起…"],
                  ["家庭动词", "cook 做饭 · clean 打扫 · take 拍（照）"]],
  phonics=dict(tip="字母组合 ck 发 /k/", words="sock 袜子 · duck 鸭子 · clock 钟"),
  s5_task="这一步我们要做的：把家庭活动的单词收进小背包！",
  s5_voice="今天我们学会了一家人的活动，还会说 We ... together 我们一起做什么。回家就能和家人用英语聊天啦！",
  boss=dict(title="Boss 关：家庭活动大挑战", type="mc",
            q="大 Boss：爸爸喜欢钓鱼，怎么用英语说？",
            opts=["My father likes fishing.", "My father like fishing.", "My father likes go fishing."],
            ok=0, hint="喜欢做某事用 like + doing，三单加 s：likes fishing"),
  s6_task="这一步我们要做的：打败家庭活动大 Boss，赢双倍星星！",
  s6_voice="最后的大 Boss 来啦！爸爸是第三人称单数，喜欢要说 likes，钓鱼用 fishing。选对奖励两颗星！",
  parent=dict(summary="认识家庭活动，会用 We ... together 表达一起做，理解 like + doing。",
              attention="第三人称单数 likes 与 go→going/fishing 的变化是难点，重点看 Boss 关。",
              tip="本课约 8 分钟；可让孩子说说周末和家人一起做的事。"),
),

dict(
  id="english-3-016", grade=3, term="下册", unit="Unit 6 My Home",
  file_unit="Unit6-MyHome", title="我的家", module="vocab", difficulty="基础",
  summary="房间单词与 There is 表达",
  keywords=["家", "home", "房间", "There is"],
  prereq=[], fileName="英语-三下-Unit6-MyHome-english-3-016-我的家.html",
  scene=dict(h2="欢迎来我家", text="Binbin 邀请朋友来家里做客，他要带朋友参观客厅、卧室、厨房……把家里的房间都介绍一下。",
             question="想一想：客厅、卧室、厨房用英语怎么说？", hint="跟 Binbin 一起参观他的家！"),
  s1_task="咱们这一步要做的：学会用英语介绍家里的房间！",
  s1_voice="Binbin 邀请朋友来家里做客，要带朋友参观客厅、卧室、厨房。今天我们学会家里的房间和 There is 句型。",
  words_title="单词大本营：我的家", words_intro="点一点卡片，认识这些房间，跟读一遍吧！",
  s2_task="这一步我们要做的：认识房间的单词，点卡片听发音！",
  s2_voice="家里有卧室、客厅、浴室、厨房、书房，还有餐厅。客厅里有沙发，卧室里有床。点一点卡片，跟着读一读。",
  words=[dict(e="home", z="家", em="🏠"), dict(e="bedroom", z="卧室", em="🛏️"), dict(e="living room", z="客厅", em="🛋️"),
         dict(e="bathroom", z="浴室", em="🛁"), dict(e="kitchen", z="厨房", em="🍳"), dict(e="study", z="书房", em="📚"),
         dict(e="dining room", z="餐厅", em="🍽️"), dict(e="sofa", z="沙发", em="🛋️"), dict(e="bed", z="床", em="🛏️"),
         dict(e="door", z="门", em="🚪")],
  pattern=dict(title="句型魔法：某处有…", sentence=["There", "is", "a", "sofa", "in", "the", "living", "room", "."], zh="客厅里有一张沙发。",
               desc="This is my home. 这是我的家。 ｜ There is ... in ... 在某处有… ｜ Where is ...? …在哪里？"),
  order=dict(zh="帮 Binbin 说「客厅里有一张沙发」", words=["There", "is", "a", "sofa", "in", "the", "living", "room", "."], right=[0, 1, 2, 3, 4, 5, 6, 7, 8],
             hint="某处有某物用 There is ... in ..."),
  s3_task="这一步我们要做的：看 There is 怎么用，再拼一个长句子！",
  s3_voice="想说某处有某物，用 There is 加上东西，再用 in the 加上房间。看句子拼出来，这个句子有点长，你要耐心拼完哦。",
  quiz=[dict(q="「这是我的家」用英语怎么说？", opts=["This is my home.", "This is my bedroom.", "Where is my home?"], ok=0, hint="home 是家"),
        dict(q="kitchen 是？", opts=["厨房", "客厅", "卧室"], ok=0, hint="kitchen 是厨房"),
        dict(q="There is a bed in the bedroom. 的意思是？", opts=["卧室里有一张床。", "床在客厅里。", "卧室是床。"], ok=0, hint="There is ... in ... 是在…里有…")],
  s4_task="这一步我们要做的：连闯三道小题，把房间单词用起来！",
  s4_voice="现在轮到你啦！三道小题，考考房间的单词和 There is 句型。答对就能得到星星哦。",
  summary_points=[["房间单词", "bedroom 卧室 · living room 客厅 · kitchen 厨房 · bathroom 浴室 · study 书房"],
                  ["我的家", "This is my home. 这是我的家。"],
                  ["有…", "There is ... in ... 在某处有…"]],
  phonics=dict(tip="字母组合 oo 常发 /ʊ/", words="book 书 · look 看 · good 好"),
  s5_task="这一步我们要做的：把房间的单词收进小背包！",
  s5_voice="今天我们认识了家里的房间，还学会了 There is 某处有某物。以后就能向朋友介绍你的家了！",
  boss=dict(title="Boss 关：家居大挑战", type="mc",
            q="大 Boss：你想说「客厅里有一张沙发」，怎么说？",
            opts=["There is a sofa in the living room.", "There is a living room in the sofa.", "This is a sofa in the living room."],
            ok=0, hint="某处有某物用 There is ... in ..."),
  s6_task="这一步我们要做的：打败家居大 Boss，赢双倍星星！",
  s6_voice="最后的大 Boss 来啦！它想知道你会不会用 There is。记住：某处有某物，先说 There is，再说东西，最后说在哪里。选对奖励两颗星！",
  parent=dict(summary="认识房间单词，会用 This is my home 与 There is ... in ... 介绍家的布局。",
              attention="There is 句型语序（先 There is 后地点）易倒；see 也提醒 There is + 单数。",
              tip="本课约 8 分钟；可让孩子带家长用英语逛一遍自己的家。"),
),

# ============================ 四年级上册（已在库，补课件） ============================
dict(
  id="english-4-001", grade=4, term="上册", unit="Unit 1 Sports and Games",
  file_unit="Unit1-SportsAndGames", title="运动与游戏", module="vocab", difficulty="基础",
  summary="运动词汇与 I like 频率表达",
  keywords=["运动", "sports", "频率", "often"],
  prereq=[], fileName="英语-四上-Unit1-SportsAndGames-english-4-001-运动与游戏.html",
  scene=dict(h2="运动会报名", text="学校要开运动会啦！跑步、篮球、乒乓球、跳绳……Binbin 想报他最擅长的运动，还要问问小伙伴喜欢什么。",
             question="想一想：你会用英语说「我喜欢跑步」吗？", hint="运动会等你来报名！"),
  s1_task="咱们这一步要做的：学会用英语说喜欢的运动！",
  s1_voice="学校要开运动会了，跑步、篮球、乒乓球、跳绳，好多项目。Binbin 想知道小伙伴喜欢什么运动。今天我们来学运动的单词和问句。",
  words_title="单词大本营：运动与游戏", words_intro="点一点卡片，认识这些运动项目，跟读一遍吧！",
  s2_task="这一步我们要做的：认识运动的单词，点卡片听发音！",
  s2_voice="运动项目有跑步、篮球、滑旱冰、跳绳、乒乓球、游泳和足球。还有一个词 often，是经常的意思。点一点卡片，跟着读一读。",
  words=[dict(e="running", z="跑步", em="🏃"), dict(e="basketball", z="篮球", em="🏀"), dict(e="roller skating", z="滑旱冰", em="⛸️"),
         dict(e="jumping rope", z="跳绳", em="🪢"), dict(e="ping-pong", z="乒乓球", em="🏓"), dict(e="swimming", z="游泳", em="🏊"),
         dict(e="football", z="足球", em="⚽"), dict(e="interesting", z="有趣的", em="✨"), dict(e="often", z="经常", em="🔁")],
  pattern=dict(title="句型魔法：我喜欢…", sentence=["I", "like", "running", "."], zh="我喜欢跑步。",
               desc="What's your favourite sport? 你最喜欢的运动是什么？ ｜ I like running. 我喜欢跑步。 ｜ What about basketball? 篮球怎么样？"),
  order=dict(zh="帮 Binbin 说「我喜欢跑步」", words=["I", "like", "running", "."], right=[0, 1, 2, 3],
             hint="喜欢运动用 I like + 动词 ing，如 running"),
  s3_task="这一步我们要做的：看 I like 怎么用，再拼一句！",
  s3_voice="说喜欢的运动，用 I like 加上运动名。注意动词要加 ing，比如 run 变成 running。看句子拼出来，然后你来拼一句。",
  quiz=[dict(q="「你最喜欢的运动是什么？」用英语怎么说？", opts=["What's your favourite sport?", "What sport is it?", "I like sports."], ok=0, hint="问最喜欢的运动用 favourite sport"),
        dict(q="jumping rope 是？", opts=["跳绳", "跑步", "游泳"], ok=0, hint="jumping rope 是跳绳"),
        dict(q="What about basketball? 的意思是？", opts=["篮球怎么样？", "什么是篮球？", "我喜欢篮球。"], ok=0, hint="What about ...? 是…怎么样？")],
  s4_task="这一步我们要做的：连闯三道小题，把运动单词用起来！",
  s4_voice="现在轮到你啦！三道小题，考考运动的单词和 favourite 句型。答对就能得到星星哦。",
  summary_points=[["运动单词", "running 跑步 · basketball 篮球 · ping-pong 乒乓球 · swimming 游泳"],
                  ["询问喜好", "What's your favourite sport? 你最喜欢的运动是什么？"],
                  ["表达喜欢", "I like ... 我喜欢…（动词要加 ing）"]],
  phonics=dict(tip="字母组合 sk 发 /sk/", words="skate 滑冰 · skating 滑冰 · skip 跳"),
  s5_task="这一步我们要做的：把运动的单词收进小背包！",
  s5_voice="今天我们认识了很多运动，还学会了说最喜欢的运动。运动会报名的时候，你就能用英语说出自己喜欢的项目啦！",
  boss=dict(title="Boss 关：运动会大挑战", type="mc",
            q="大 Boss：你想问朋友「你经常跑步吗？」，怎么说？",
            opts=["Do you often run?", "Do you like running?", "What's your favourite sport?"],
            ok=0, hint="问经常做某事用 Do you often ...?"),
  s6_task="这一步我们要做的：打败运动会大 Boss，赢双倍星星！",
  s6_voice="最后的大 Boss 来啦！它想知道你会不会问频率。记住用 Do you often。选对奖励两颗星！",
  parent=dict(summary="认识运动单词，会用 What's your favourite sport? 与 I like + ing 表达，理解 often。",
              attention="动词加 ing（run→running）是重点；often 是频率词，Boss 关练 Do you often。",
              tip="本课约 8 分钟；可让孩子用英语说出 3 个喜欢的运动。"),
),

dict(
  id="english-4-002", grade=4, term="上册", unit="Unit 2 On the Weekend",
  file_unit="Unit2-OnTheWeekend", title="周末活动", module="vocab", difficulty="基础",
  summary="周末活动词汇与一般现在时",
  keywords=["周末", "weekend", "活动", "often"],
  prereq=[], fileName="英语-四上-Unit2-OnTheWeekend-english-4-002-周末活动.html",
  scene=dict(h2="周末去哪儿", text="周末到了，Binbin 有时去绘画俱乐部，有时去爬山、摘水果。他很好奇：小伙伴周末都做什么呢？",
             question="想一想：你会用英语说「我周末经常去公园」吗？", hint="周末活动真丰富，学起来！"),
  s1_task="咱们这一步要做的：学会用英语说周末活动！",
  s1_voice="周末到了，Binbin 的活动可真多：去绘画俱乐部、爬山、摘水果。他很好奇小伙伴周末做什么。今天我们学会这些活动。",
  words_title="单词大本营：周末活动", words_intro="点一点卡片，认识这些周末活动，跟读一遍吧！",
  s2_task="这一步我们要做的：认识周末活动的单词，点卡片听发音！",
  s2_voice="周末可以看望爷爷奶奶、去绘画俱乐部、爬山、摘水果，还能玩电脑游戏、钓鱼、去公园。点一点卡片，跟着读一读。",
  words=[dict(e="visit one's grandparents", z="看望祖父母", em="👵👴"), dict(e="go to a drawing club", z="去绘画俱乐部", em="🎨"),
         dict(e="climb a hill", z="爬山", em="⛰️"), dict(e="pick fruit", z="摘水果", em="🍎"),
         dict(e="play computer games", z="玩电脑游戏", em="🎮"), dict(e="go fishing", z="钓鱼", em="🎣"),
         dict(e="go to the park", z="去公园", em="🌳"), dict(e="draw pictures", z="画画", em="✏️")],
  pattern=dict(title="句型魔法：你周末做什么？", sentence=["I", "often", "go", "to", "the", "park", "."], zh="我经常去公园。",
               desc="What do you do on the weekend? 你周末做什么？ ｜ I often ... 我经常… ｜ Do you often ...? 你经常…吗？"),
  order=dict(zh="帮 Binbin 说「我经常去绘画俱乐部」", words=["I", "often", "go", "to", "a", "drawing", "club", "."], right=[0, 1, 2, 3, 4, 5, 6, 7],
             hint="经常做某事用 I often ...，去俱乐部用 go to a ... club"),
  s3_task="这一步我们要做的：看 often 怎么用，再拼一个长句子！",
  s3_voice="周末经常做的事，用 I often 加上活动。看句子拼出来，然后你来把「我经常去绘画俱乐部」拼出来。",
  quiz=[dict(q="「你周末做什么？」用英语怎么说？", opts=["What do you do on the weekend?", "What do you do after school?", "What's your favourite sport?"], ok=0, hint="问周末用 on the weekend"),
        dict(q="climb a hill 是？", opts=["爬山", "游泳", "跳绳"], ok=0, hint="climb a hill 是爬山"),
        dict(q="I often go fishing. 的意思是？", opts=["我经常去钓鱼。", "我周末去钓鱼。", "我喜欢钓鱼。"], ok=0, hint="often 是经常")],
  s4_task="这一步我们要做的：连闯三道小题，把周末活动用起来！",
  s4_voice="现在轮到你啦！三道小题，考考周末的单词和 often。答对就能得到星星哦。",
  summary_points=[["周末活动", "visit grandparents 看望祖父母 · climb a hill 爬山 · pick fruit 摘水果"],
                  ["询问周末", "What do you do on the weekend? 你周末做什么？"],
                  ["频率表达", "I often ... 我经常…"]],
  phonics=dict(tip="字母组合 cl 发 /kl/", words="climb 爬 · club 俱乐部 · class 班级"),
  s5_task="这一步我们要做的：把周末活动的单词收进小背包！",
  s5_voice="今天我们学会了很多周末活动，还会说 I often 我经常做什么。下次就能和小伙伴聊周末安排了！",
  boss=dict(title="Boss 关：周末大挑战", type="mc",
            q="大 Boss：你想问朋友「你周末经常摘水果吗？」，怎么说？",
            opts=["Do you often pick fruit on the weekend?", "What do you do on the weekend?", "I often pick fruit."],
            ok=0, hint="问经常做某事用 Do you often ...?"),
  s6_task="这一步我们要做的：打败周末大 Boss，赢双倍星星！",
  s6_voice="最后的大 Boss 来啦！问别人周末经常做的事，用 Do you often 加上活动。选对奖励两颗星！",
  parent=dict(summary="认识周末活动，会用 What do you do on the weekend? 询问、I often ... 表达频率。",
              attention="often 在主语后（I often go）；on the weekend 的介词 on 别漏。",
              tip="本课约 8 分钟；可让孩子用 I often ... 说 3 个周末常做的事。"),
),

dict(
  id="english-4-003", grade=4, term="上册", unit="Unit 3 Transportation",
  file_unit="Unit3-Transportation", title="交通方式", module="vocab", difficulty="提高",
  summary="交通方式词汇与出行表达",
  keywords=["交通", "transportation", "出行"],
  prereq=[], fileName="英语-四上-Unit3-Transportation-english-4-003-交通方式.html",
  scene=dict(h2="怎么去学校", text="早上，大家用不同的方式去学校：有的坐公交，有的骑车，有的走路。Binbin 想知道你每天怎么上学。",
             question="想一想：你会用英语说「我坐公交去学校」吗？", hint="交通方式学起来，出门问路不用愁！"),
  s1_task="咱们这一步要做的：学会用英语说怎么去学校！",
  s1_voice="早上大家去学校的方式各不相同：有的坐公交，有的骑车，有的走路。Binbin 想问问你每天怎么上学。今天来学交通方式。",
  words_title="单词大本营：交通方式", words_intro="点一点卡片，认识这些交通工具，跟读一遍吧！",
  s2_task="这一步我们要做的：认识交通工具的单词，点卡片听发音！",
  s2_voice="出行可以坐公共汽车、小汽车、自行车、火车、地铁、飞机、轮船，还可以打车，或者步行。点一点卡片，跟着读一读。",
  words=[dict(e="bus", z="公共汽车", em="🚌"), dict(e="car", z="小汽车", em="🚗"), dict(e="bike", z="自行车", em="🚲"),
         dict(e="train", z="火车", em="🚆"), dict(e="subway", z="地铁", em="🚇"), dict(e="plane", z="飞机", em="✈️"),
         dict(e="ship", z="轮船", em="🚢"), dict(e="taxi", z="出租车", em="🚕"), dict(e="walk", z="步行", em="🚶")],
  pattern=dict(title="句型魔法：你怎么去…？", sentence=["I", "go", "to", "school", "by", "bus", "."], zh="我坐公共汽车去学校。",
               desc="How do you go to ...? 你怎么去…？ ｜ I go by ... 我坐…去。 ｜ I walk to school. 我步行去学校。"),
  order=dict(zh="帮 Binbin 问「你怎么去学校？」", words=["How", "do", "you", "go", "to", "school", "?"], right=[0, 1, 2, 3, 4, 5, 6],
             hint="问交通方式用 How do you go to ...?"),
  s3_task="这一步我们要做的：看 How do you go 怎么用，再拼一个问句！",
  s3_voice="想知道别人怎么去某地，用 How do you go to 加上地方。坐什么去用 by 加上交通工具。看句子拼出来，然后你来拼问句。",
  quiz=[dict(q="「你怎么去学校？」用英语怎么说？", opts=["How do you go to school?", "What do you do at school?", "Where is your school?"], ok=0, hint="问怎么去用 How do you go to ...?"),
        dict(q="subway 是？", opts=["地铁", "公交", "火车"], ok=0, hint="subway 是地铁"),
        dict(q="I go by plane. 的意思是？", opts=["我坐飞机去。", "我坐火车去。", "我骑自行车去。"], ok=0, hint="by plane 是坐飞机")],
  s4_task="这一步我们要做的：连闯三道小题，把交通方式用起来！",
  s4_voice="现在轮到你啦！三道小题，考考交通工具的单词和问句。答对就能得到星星哦。",
  summary_points=[["交通单词", "bus 公交 · bike 自行车 · subway 地铁 · plane 飞机 · walk 步行"],
                  ["询问方式", "How do you go to ...? 你怎么去…？"],
                  ["回答", "I go by ... 我坐…去；I walk. 我步行。"]],
  phonics=dict(tip="字母组合 tr 发 /tr/", words="train 火车 · tree 树 · truck 卡车"),
  s5_task="这一步我们要做的：把交通的单词收进小背包！",
  s5_voice="今天我们学会了很多交通工具，还会问别人怎么去某个地方。下次出门，你也能用英语交流啦！",
  boss=dict(title="Boss 关：出行大挑战", type="mc",
            q="大 Boss：你想说「我走路去上学」，怎么说？",
            opts=["I walk to school.", "I go to school by walk.", "I walk school."],
            ok=0, hint="步行用动词 walk，不加 by；to school 别忘了"),
  s6_task="这一步我们要做的：打败出行大 Boss，赢双倍星星！",
  s6_voice="最后的大 Boss 来啦！走路用 walk，是动词，不用 by。选对奖励两颗星！",
  parent=dict(summary="认识交通方式，会用 How do you go to ...? 询问、I go by ... / I walk 回答。",
              attention="步行用 walk（不加 by），乘车用 by + 工具；这是最容易错的一处。",
              tip="本课约 8 分钟；可让孩子用英语说说家人上班上学的出行方式。"),
),

dict(
  id="english-4-004", grade=4, term="上册", unit="Unit 4 Asking for Help",
  file_unit="Unit4-AskingForHelp", title="求助用语", module="listen", difficulty="基础",
  summary="礼貌求助与应答的日常用语",
  keywords=["求助", "help", "礼貌用语"],
  prereq=[], fileName="英语-四上-Unit4-AskingForHelp-english-4-004-求助用语.html",
  scene=dict(h2="迷路的小游客", text="小游客在街上迷路了，他要用英语礼貌地问路：「请问，书店在哪里？」还要会说「谢谢」「不客气」。",
             question="想一想：你会用英语说「请问…在哪里？」吗？", hint="礼貌求助，走到哪里都不怕！"),
  s1_task="咱们这一步要做的：学会有礼貌地用英语求助！",
  s1_voice="一位小游客在街上迷路了，想用英语问路。他先要说 Excuse me 打扰一下，再问书店在哪里。今天来学礼貌求助的句子。",
  words_title="单词大本营：求助用语", words_intro="点一点卡片，记住这些礼貌用语，跟读一遍吧！",
  s2_task="这一步我们要做的：认识求助的用语，点卡片听发音！",
  s2_voice="求助时先说 Excuse me 打扰一下，再说 Where is 哪里。别人帮你后要说 Thanks 谢谢，对方会说 You're welcome 不客气。点一点卡片，跟着读一读。",
  words=[dict(e="Excuse me", z="打扰一下", em="🙋"), dict(e="Can I help you?", z="需要帮忙吗？", em="🤝"),
         dict(e="Sure", z="当然", em="👍"), dict(e="Thanks", z="谢谢", em="🙏"),
         dict(e="You're welcome", z="不客气", em="😊"), dict(e="Where is...?", z="…在哪里？", em="🗺️"),
         dict(e="far", z="远的", em="🚶"), dict(e="near", z="近的", em="📍")],
  pattern=dict(title="句型魔法：请问…在哪里？", sentence=["Excuse", "me,", "where", "is", "the", "bookshop", "?"], zh="打扰一下，书店在哪里？",
               desc="Excuse me, where is ...? 请问…在哪里？ ｜ It's far from here. 离这里很远。 ｜ Can I help you? 需要帮忙吗？"),
  order=dict(zh="帮小游客问「打扰一下，书店在哪里？」", words=["Excuse", "me,", "where", "is", "the", "bookshop", "?"], right=[0, 1, 2, 3, 4, 5, 6],
             hint="问路先 Excuse me，再加 where is ..."),
  s3_task="这一步我们要做的：看 Excuse me 怎么用，再拼一个问句！",
  s3_voice="问路前先说 Excuse me，这样最有礼貌。然后说 where is 加上要去的地方。看句子拼出来，然后你来拼这个问句。",
  quiz=[dict(q="「打扰一下，邮局在哪里？」用英语怎么说？", opts=["Excuse me, where is the post office?", "Where are you?", "Can I help you?"], ok=0, hint="问邮局用 Excuse me, where is the post office?"),
        dict(q="Can I help you? 的意思是？", opts=["需要帮忙吗？", "你是谁？", "你去哪？"], ok=0, hint="Can I help you? 是询问需要帮助吗"),
        dict(q="别人帮你之后，你该说什么？", opts=["Thanks.", "Excuse me.", "Where is it?"], ok=0, hint="得到帮助后说 Thanks 谢谢")],
  s4_task="这一步我们要做的：连闯三道小题，把求助用语用起来！",
  s4_voice="现在轮到你啦！三道小题，考考求助的礼貌用语。答对就能得到星星哦。",
  summary_points=[["礼貌开头", "Excuse me 打扰一下（问路、求助前先说）"],
                  ["问路句型", "Where is ...? …在哪里？"],
                  ["礼貌应答", "Can I help you? 需要帮忙吗？ ｜ Thanks. 谢谢。 ｜ You're welcome. 不客气。"]],
  phonics=dict(tip="字母组合 ou 常发 /aʊ/", words="about 关于 · house 房子 · sound 声音"),
  s5_task="这一步我们要做的：把求助的用语收进小背包！",
  s5_voice="今天我们学会了有礼貌地求助：先 Excuse me，再问 Where is，最后说 Thanks。出门在外，礼貌用语最管用！",
  boss=dict(title="Boss 关：求助大挑战", type="mc",
            q="大 Boss：你想请别人帮忙，怎么最有礼貌地开口？",
            opts=["Excuse me, can you help me?", "Give me help!", "Hey, where is it?"],
            ok=0, hint="求助先用 Excuse me 礼貌开场，再说 can you help me"),
  s6_task="这一步我们要做的：打败求助大 Boss，赢双倍星星！",
  s6_voice="最后的大 Boss 来啦！求助时先礼貌地说 Excuse me，再加上 can you help me。选对奖励两颗星！",
  parent=dict(summary="掌握 Excuse me / Where is / Can I help / Thanks / You're welcome 等礼貌求助用语。",
              attention="Excuse me 是万能礼貌开场；Can I help you? 与 Can you help me? 角色易反。",
              tip="本课约 8 分钟；可在家模拟问路场景，让孩子练习完整对话。"),
),

dict(
  id="english-4-005", grade=4, term="上册", unit="Unit 5 Safety",
  file_unit="Unit5-Safety", title="安全规则", module="listen", difficulty="提高",
  summary="安全规则与祈使句表达",
  keywords=["安全", "safety", "祈使句"],
  prereq=[], fileName="英语-四上-Unit5-Safety-english-4-005-安全规则.html",
  scene=dict(h2="马路安全小卫士", text="过马路要停、看、听，不可以在街上乱跑，更不能玩火。Binbin 要当安全小卫士，把安全规则教给小伙伴！",
             question="想一想：你会用英语说「不要跑！」吗？", hint="安全第一，学会这些英语能保护自己！"),
  s1_task="咱们这一步要做的：学会用英语说安全规则！",
  s1_voice="过马路要停、看、听，不可以在街上乱跑，更不能玩火。Binbin 要当安全小卫士，把这些规则用英语告诉小伙伴。今天来学安全表达。",
  words_title="单词大本营：安全规则", words_intro="点一点卡片，记住这些保命的安全用语，跟读一遍吧！",
  s2_task="这一步我们要做的：认识安全的用语，点卡片听发音！",
  s2_voice="过马路前要 Stop 停、Look 看、Listen 听。不可以在街上跑，不能玩火。还有 Be careful 小心。点一点卡片，跟着读一读。",
  words=[dict(e="safety", z="安全", em="🛡️"), dict(e="careful", z="小心的", em="⚠️"), dict(e="Don't run", z="不要跑", em="🛑"),
         dict(e="Don't play with fire", z="不要玩火", em="🔥"), dict(e="stop", z="停", em="✋"), dict(e="look", z="看", em="👀"),
         dict(e="listen", z="听", em="👂"), dict(e="cross the street", z="过马路", em="🚸"), dict(e="wait", z="等待", em="⏳")],
  pattern=dict(title="句型魔法：不要…", sentence=["Don't", "run", "in", "the", "street", "."], zh="不要在街上跑。",
               desc="Don't ... 不要…（祈使句否定） ｜ Stop! Look! Listen! 停！看！听！ ｜ Be careful! 小心！"),
  order=dict(zh="帮小卫士说「不要玩火」", words=["Don't", "play", "with", "fire", "."], right=[0, 1, 2, 3, 4],
             hint="禁止做某事用 Don't + 动词原形"),
  s3_task="这一步我们要做的：看 Don't 怎么用，再拼一条安全规则！",
  s3_voice="告诉别人不要做某事，用 Don't 加上动词。比如不要玩火，就是 Don't play with fire。看句子拼出来，然后你来拼一条规则。",
  quiz=[dict(q="「不要在街上跑」用英语怎么说？", opts=["Don't run in the street.", "Run in the street.", "Don't stop in the street."], ok=0, hint="禁止用 Don't + 动词"),
        dict(q="Be careful. 的意思是？", opts=["小心！", "快跑！", "别走！"], ok=0, hint="Be careful 是小心"),
        dict(q="过马路前应该怎么做？", opts=["Stop! Look! Listen!", "Run quickly!", "Play in the street!"], ok=0, hint="过马路前要停、看、听")],
  s4_task="这一步我们要做的：连闯三道小题，把安全用语用起来！",
  s4_voice="现在轮到你啦！三道小题，考考安全规则。答对就能得到星星哦。",
  summary_points=[["安全规则", "Don't run 不要跑 · Don't play with fire 不要玩火"],
                  ["三字口诀", "Stop! Look! Listen! 停！看！听！"],
                  ["提醒小心", "Be careful! 小心！"]],
  phonics=dict(tip="单词 Don't 中 o 读 /əʊ/，careful 中 ca 读 /eə/", words="careful 小心 · share 分享 · square 广场"),
  s5_task="这一步我们要做的：把安全规则收进小背包！",
  s5_voice="今天我们学会了几条重要的安全规则：不要跑、不要玩火，过马路要停看听。这些英语关键时刻能保护你！",
  boss=dict(title="Boss 关：安全大挑战", type="mc",
            q="大 Boss：看到小朋友在玩火，你会怎么说？",
            opts=["Don't play with fire!", "Don't run!", "Play with fire carefully!"],
            ok=0, hint="禁止玩火用 Don't play with fire"),
  s6_task="这一步我们要做的：打败安全大 Boss，赢双倍星星！",
  s6_voice="最后的大 Boss 来啦！看到小朋友玩火，要大声说 Don't play with fire！选对奖励两颗星！",
  parent=dict(summary="掌握 Don't ... 祈使句否定、Stop! Look! Listen! 与 Be careful 等安全表达。",
              attention="Don't + 动词原形是核心句型；be 动词要变 Be careful 而非 Are careful。",
              tip="本课约 8 分钟；可带孩子回忆并说出一条安全规则，强化记忆。"),
),

dict(
  id="english-4-006", grade=4, term="上册", unit="Unit 6 Jobs",
  file_unit="Unit6-Jobs", title="职业表达", module="vocab", difficulty="基础",
  summary="职业词汇与 I want to be 表达",
  keywords=["职业", "jobs", "职业理想"],
  prereq=[], fileName="英语-四上-Unit6-Jobs-english-4-006-职业表达.html",
  scene=dict(h2="我的梦想", text="每个人都有自己的梦想职业：医生救死扶伤、老师教书育人、厨师做好吃的菜……Binbin 想知道你长大想做什么。",
             question="想一想：医生、老师、司机用英语怎么说？", hint="聊职业，聊梦想，学起来！"),
  s1_task="咱们这一步要做的：学会用英语说梦想的职业！",
  s1_voice="每个人都有梦想的职业：医生、老师、厨师……Binbin 想知道你长大想做什么。今天来学职业的单词和 I want to be 的句子。",
  words_title="单词大本营：职业", words_intro="点一点卡片，认识这些职业，跟读一遍吧！",
  s2_task="这一步我们要做的：认识职业的单词，点卡片听发音！",
  s2_voice="职业有很多：医生、护士、老师、农民、工人、厨师、司机、警察，还有工程师。点一点卡片，听听它们的英文名字，跟着读一读。",
  words=[dict(e="doctor", z="医生", em="🧑‍⚕️"), dict(e="nurse", z="护士", em="👩‍⚕️"), dict(e="teacher", z="老师", em="👩‍🏫"),
         dict(e="farmer", z="农民", em="👨‍🌾"), dict(e="worker", z="工人", em="👷"), dict(e="cook", z="厨师", em="👨‍🍳"),
         dict(e="driver", z="司机", em="🚗"), dict(e="police officer", z="警察", em="👮"), dict(e="engineer", z="工程师", em="🧑‍🔧")],
  pattern=dict(title="句型魔法：你想成为…", sentence=["I", "want", "to", "be", "a", "teacher", "."], zh="我想成为老师。",
               desc="What does your father do? 你爸爸是做什么的？ ｜ He's a doctor. 他是医生。 ｜ I want to be a ... 我想成为…"),
  order=dict(zh="帮 Binbin 说「我想成为老师」", words=["I", "want", "to", "be", "a", "teacher", "."], right=[0, 1, 2, 3, 4, 5, 6],
             hint="想成为用 I want to be a ..."),
  s3_task="这一步我们要做的：看 I want to be 怎么用，再拼一句！",
  s3_voice="说自己想成为什么，用 I want to be 加上职业。看句子拼出来，然后你来拼「我想成为老师」这句。",
  quiz=[dict(q="「你爸爸是做什么的？」用英语怎么说？", opts=["What does your father do?", "What is your father?", "Who is your father?"], ok=0, hint="问职业用 What does ... do?"),
        dict(q="police officer 是？", opts=["警察", "医生", "司机"], ok=0, hint="police officer 是警察"),
        dict(q="I want to be a doctor. 的意思是？", opts=["我想当医生。", "我喜欢医生。", "我是医生。"], ok=0, hint="want to be 是想成为")],
  s4_task="这一步我们要做的：连闯三道小题，把职业单词用起来！",
  s4_voice="现在轮到你啦！三道小题，考考职业的单词和句型。答对就能得到星星哦。",
  summary_points=[["职业单词", "doctor 医生 · teacher 老师 · cook 厨师 · driver 司机 · police officer 警察"],
                  ["询问职业", "What does ... do? …是做什么的？"],
                  ["梦想职业", "I want to be a ... 我想成为…"]],
  phonics=dict(tip="职业词尾 er 常读 /ə/", words="teacher 老师 · driver 司机 · worker 工人 · farmer 农民"),
  s5_task="这一步我们要做的：把职业的单词收进小背包！",
  s5_voice="今天我们认识了很多职业，还学会了说我长大想做什么。以后聊梦想的时候，你就能用英语表达啦！",
  boss=dict(title="Boss 关：职业大挑战", type="mc",
            q="大 Boss：姐姐是护士，你想说「她是护士」，怎么说？",
            opts=["She's a nurse.", "He's a nurse.", "She's a doctor."],
            ok=0, hint="她是…用 She's a ...，注意女生用 she"),
  s6_task="这一步我们要做的：打败职业大 Boss，赢双倍星星！",
  s6_voice="最后的大 Boss 来啦！姐姐是女生，要说 She's a nurse。选对奖励两颗星！",
  parent=dict(summary="认识职业单词，会用 What does ... do? 询问、I want to be a ... 表达职业理想。",
              attention="he/she 性别易混；What does ... do? 中的 does 后动词用原形。",
              tip="本课约 8 分钟；可让孩子用英语介绍家人的职业和自己的理想。"),
),

# ============================ 四年级下册 ============================
dict(
  id="english-4-011", grade=4, term="下册", unit="Unit 1 My Neighbourhood",
  file_unit="Unit1-MyNeighbourhood", title="我的社区", module="vocab", difficulty="基础",
  summary="社区地点与问路指路表达",
  keywords=["社区", "neighbourhood", "问路", "指路"],
  prereq=[], fileName="英语-四下-Unit1-MyNeighbourhood-english-4-011-我的社区.html",
  scene=dict(h2="社区寻宝", text="Binbin 搬到新社区，要去邮局寄信、去超市买东西。他要学会看方向：直走、左转、右转，还有各个地方在哪儿。",
             question="想一想：邮局、超市用英语怎么说？", hint="学会认路，走遍社区都不怕！"),
  s1_task="咱们这一步要做的：学会用英语问路和指路！",
  s1_voice="Binbin 搬到新社区，要去邮局寄信、去超市买东西。他得学会问地方在哪、怎么走。今天来学社区的地点和指路用语。",
  words_title="单词大本营：我的社区", words_intro="点一点卡片，认识社区里的地方和方向，跟读一遍吧！",
  s2_task="这一步我们要做的：认识社区的单词，点卡片听发音！",
  s2_voice="社区里有餐馆、邮局、银行、超市、医院、书店。方向有直行、左转、右转，还有十字路口。点一点卡片，跟着读一读。",
  words=[dict(e="across from", z="在对面", em="↔️"), dict(e="next to", z="紧邻", em="↔️"), dict(e="between", z="在…之间", em="➡️⬅️"),
         dict(e="restaurant", z="餐馆", em="🍽️"), dict(e="post office", z="邮局", em="📮"), dict(e="bank", z="银行", em="🏦"),
         dict(e="grocery", z="食品杂货店", em="🛒"), dict(e="supermarket", z="超市", em="🛒"), dict(e="hospital", z="医院", em="🏥"),
         dict(e="bookshop", z="书店", em="📚"), dict(e="turn left", z="向左转", em="⬅️"), dict(e="turn right", z="向右转", em="➡️"),
         dict(e="go straight", z="直行", em="⬆️"), dict(e="crossroads", z="十字路口", em="✛")],
  pattern=dict(title="句型魔法：直走再左转", sentence=["Turn", "left", "at", "the", "crossroads", "."], zh="在十字路口向左转。",
               desc="Where is ...? …在哪？ ｜ It's across from ... 在…对面。 ｜ Turn left / right 左转 / 右转，Go straight 直行。"),
  order=dict(zh="帮 Binbin 说「直走然后左转」", words=["Go", "straight", "and", "turn", "left", "."], right=[0, 1, 2, 3, 4, 5],
             hint="直行用 go straight，左转用 turn left，中间用 and 连接"),
  s3_task="这一步我们要做的：看指路的句子怎么用，再拼一句！",
  s3_voice="指路的时候，直走说 go straight，左转说 turn left，右转说 turn right。看句子拼出来，然后你来拼一句指路的话。",
  quiz=[dict(q="「邮局在哪里？」用英语怎么说？", opts=["Where is the post office?", "What is the post office?", "Is it the post office?"], ok=0, hint="问地点用 Where is ...?"),
        dict(q="turn right 是？", opts=["向右转", "向左转", "直行"], ok=0, hint="turn right 是向右转"),
        dict(q="It's across from the school. 的意思是？", opts=["它在学校对面。", "它紧挨着学校。", "它在学校前面。"], ok=0, hint="across from 是在对面")],
  s4_task="这一步我们要做的：连闯三道小题，把社区地点用起来！",
  s4_voice="现在轮到你啦！三道小题，考考社区的地点和方向。答对就能得到星星哦。",
  summary_points=[["方位词", "across from 在对面 · next to 紧邻 · between 在…之间"],
                  ["地点单词", "post office 邮局 · bank 银行 · supermarket 超市 · hospital 医院"],
                  ["指路", "Go straight 直行 · Turn left 左转 · Turn right 右转"]],
  phonics=dict(tip="字母组合 oa 常发 /əʊ/", words="road 路 · boat 船 · coat 外套"),
  s5_task="这一步我们要做的：把社区的问路用语收进小背包！",
  s5_voice="今天我们学会了社区的地点和指路：直走、左转、右转。以后出门问路，你也能用英语啦！",
  boss=dict(title="Boss 关：社区大挑战", type="mc",
            q="大 Boss：你想说「超市在银行旁边」，怎么说？",
            opts=["The supermarket is next to the bank.", "The supermarket is across from the bank.", "The supermarket is between the bank."],
            ok=0, hint="旁边用 next to，对面用 across from，两者不要混"),
  s6_task="这一步我们要做的：打败社区大 Boss，赢双倍星星！",
  s6_voice="最后的大 Boss 来啦！超市在银行旁边，要用 next to，不是 across from。选对奖励两颗星！",
  parent=dict(summary="认识社区地点与方位，会用 Where is ...? 问路、turn left/right/go straight 指路。",
              attention="across from（对面）与 next to（旁边）易混；between 后接两个对象。",
              tip="本课约 8 分钟；可和孩子在地图上模拟问路对话。"),
),

dict(
  id="english-4-012", grade=4, term="下册", unit="Unit 2 Cities",
  file_unit="Unit2-Cities", title="城市", module="vocab", difficulty="基础",
  summary="城市地点与 There is 表达",
  keywords=["城市", "cities", "地点", "There is"],
  prereq=[], fileName="英语-四下-Unit2-Cities-english-4-012-城市.html",
  scene=dict(h2="城市大发现", text="周末，Binbin 一家去城市里玩：看博物馆、逛动物园、走过大桥、登上高塔……城市里好玩的地方真多！",
             question="想一想：博物馆、动物园、大桥用英语怎么说？", hint="一起探索城市里的好地方！"),
  s1_task="咱们这一步要做的：学会用英语说城市里的地方！",
  s1_voice="周末，Binbin 一家去城市里玩，看了博物馆、动物园，还走过大桥。今天来学城市里的地点和 There is 句型。",
  words_title="单词大本营：城市", words_intro="点一点卡片，认识城市里的地方，跟读一遍吧！",
  s2_task="这一步我们要做的：认识城市地点的单词，点卡片听发音！",
  s2_voice="城市里有博物馆、体育场、动物园、大桥、广场，还有宾馆和高塔。点一点卡片，听听它们的英文名字，跟着读一读。",
  words=[dict(e="city", z="城市", em="🏙️"), dict(e="place", z="地方", em="📍"), dict(e="street", z="街道", em="🛣️"),
         dict(e="museum", z="博物馆", em="🏛️"), dict(e="stadium", z="体育场", em="🏟️"), dict(e="zoo", z="动物园", em="🦁"),
         dict(e="bridge", z="桥", em="🌉"), dict(e="square", z="广场", em="⛲"), dict(e="hotel", z="宾馆", em="🏨"),
         dict(e="tower", z="塔", em="🗼")],
  pattern=dict(title="句型魔法：某处有…", sentence=["There", "is", "a", "big", "bridge", "in", "our", "city", "."], zh="我们城市里有一座大桥。",
               desc="Where is ...? …在哪？ ｜ It's near ... 在…附近。 ｜ There is ... in ... 在某处有…"),
  order=dict(zh="帮 Binbin 说「我们城市里有一个动物园」", words=["There", "is", "a", "zoo", "in", "our", "city", "."], right=[0, 1, 2, 3, 4, 5, 6, 7],
             hint="某处有某物用 There is ... in ..."),
  s3_task="这一步我们要做的：看 There is 怎么用，再拼一个句子！",
  s3_voice="说某个地方有什么，用 There is 加上东西，再加 in 和地点。看句子拼出来，然后你来拼一个长句。",
  quiz=[dict(q="「博物馆在哪里？」用英语怎么说？", opts=["Where is the museum?", "What is the museum?", "Is there a museum?"], ok=0, hint="问地点用 Where is ...?"),
        dict(q="stadium 是？", opts=["体育场", "动物园", "博物馆"], ok=0, hint="stadium 是体育场"),
        dict(q="There is a bridge in our city. 的意思是？", opts=["我们城市里有一座桥。", "桥在城市外面。", "我们有一座桥。"], ok=0, hint="There is ... in our city 是我们城市里有…")],
  s4_task="这一步我们要做的：连闯三道小题，把城市地点用起来！",
  s4_voice="现在轮到你啦！三道小题，考考城市的地点单词和 There is 句型。答对就能得到星星哦。",
  summary_points=[["城市地点", "museum 博物馆 · zoo 动物园 · stadium 体育场 · bridge 桥 · square 广场"],
                  ["问地点", "Where is ...? 在哪？"],
                  ["某处有…", "There is ... in ... 在某处有…"]],
  phonics=dict(tip="字母组合 ee 常发 /iː/", words="street 街道 · tree 树 · green 绿色"),
  s5_task="这一步我们要做的：把城市的单词收进小背包！",
  s5_voice="今天我们认识了城市里的好地方，还会用 There is 说某处有什么。以后介绍你住的城市，也能用英语啦！",
  boss=dict(title="Boss 关：城市大挑战", type="mc",
            q="大 Boss：你想说「动物园在公园旁边」，怎么说？",
            opts=["The zoo is next to the park.", "The zoo is across from the park.", "There is a zoo in the park."],
            ok=0, hint="旁边用 next to"),
  s6_task="这一步我们要做的：打败城市大 Boss，赢双倍星星！",
  s6_voice="最后的大 Boss 来啦！动物园在公园旁边，用 next to。选对奖励两颗星！",
  parent=dict(summary="认识城市地点，会用 Where is ...? 与 There is ... in ... 描述城市。",
              attention="There is 与 It is 的区分（There is 表示存在，It is 表示它…）；next to 表旁边。",
              tip="本课约 8 分钟；可让孩子用 There is 介绍所在城市的 3 个地方。"),
),

dict(
  id="english-4-013", grade=4, term="下册", unit="Unit 3 Travel Plans",
  file_unit="Unit3-TravelPlans", title="旅行计划", module="vocab", difficulty="提高",
  summary="旅行词汇与 be going to 表达",
  keywords=["旅行", "travel", "计划", "going to"],
  prereq=[], fileName="英语-四下-Unit3-TravelPlans-english-4-013-旅行计划.html",
  scene=dict(h2="出发去旅行", text="暑假到了！Binbin 一家要去海南旅行：坐飞机、住酒店、逛海滩、爬高山。出发前，他们要把计划说清楚。",
             question="想一想：你会用英语说「我打算去海南」吗？", hint="旅行计划学起来，出发不慌张！"),
  s1_task="咱们这一步要做的：学会用英语说旅行计划！",
  s1_voice="暑假到了，Binbin 一家要去海南旅行：坐飞机、住酒店、逛海滩、爬高山。今天来学旅行计划怎么说。",
  words_title="单词大本营：旅行计划", words_intro="点一点卡片，认识旅行要用的单词，跟读一遍吧！",
  s2_task="这一步我们要做的：认识旅行的单词，点卡片听发音！",
  s2_voice="旅行要准备的东西有地图、相机，要去的地方有海滩、高山，还要住旅馆。点一点卡片，听听它们的英文名字，跟着读一读。",
  words=[dict(e="travel", z="旅行", em="🧳"), dict(e="trip", z="旅行", em="🗺️"), dict(e="plane", z="飞机", em="✈️"),
         dict(e="train", z="火车", em="🚆"), dict(e="hotel", z="旅馆", em="🏨"), dict(e="map", z="地图", em="🗺️"),
         dict(e="camera", z="相机", em="📷"), dict(e="beach", z="海滩", em="🏖️"), dict(e="mountain", z="山", em="⛰️"),
         dict(e="vacation", z="假期", em="🏝️"), dict(e="visit", z="参观；拜访", em="👀")],
  pattern=dict(title="句型魔法：我打算去…", sentence=["I'm", "going", "to", "visit", "the", "beach", "."], zh="我打算去海滩玩。",
               desc="Where do you want to go? 你想去哪儿？ ｜ I want to go to ... 我想去…。 ｜ How will you go? By plane. 你打算怎么去？坐飞机。"),
  order=dict(zh="帮 Binbin 说「我想去海南」", words=["I", "want", "to", "go", "to", "Hainan", "."], right=[0, 1, 2, 3, 4, 5, 6],
             hint="想去某地用 I want to go to ..."),
  s3_task="这一步我们要做的：看句型怎么用，再拼一句！",
  s3_voice="说想做的事，用 I'm going to 加上动作；说想去哪里，用 I want to go to 加上地方。看句子拼出来，然后你来拼一句。",
  quiz=[dict(q="「你想去哪儿？」用英语怎么说？", opts=["Where do you want to go?", "Where are you?", "What do you want?"], ok=0, hint="问想去哪用 Where do you want to go?"),
        dict(q="beach 是？", opts=["海滩", "山", "酒店"], ok=0, hint="beach 是海滩"),
        dict(q="I'm going to visit the mountain. 的意思是？", opts=["我打算去爬山。", "我爬过山。", "我喜欢山。"], ok=0, hint="be going to 是打算做某事")],
  s4_task="这一步我们要做的：连闯三道小题，把旅行计划用起来！",
  s4_voice="现在轮到你啦！三道小题，考考旅行的单词和 be going to。答对就能得到星星哦。",
  summary_points=[["旅行单词", "travel 旅行 · map 地图 · camera 相机 · beach 海滩 · mountain 山"],
                  ["询问去处", "Where do you want to go? 你想去哪儿？"],
                  ["打算做…", "be going to ... 打算…"]],
  phonics=dict(tip="字母组合 ai 常发 /eɪ/", words="train 火车 · rain 雨 · wait 等待"),
  s5_task="这一步我们要做的：把旅行的单词收进小背包！",
  s5_voice="今天我们学会了旅行计划怎么说：想去哪里、打算做什么。下次全家旅行，你也能当小翻译啦！",
  boss=dict(title="Boss 关：旅行大挑战", type="mc",
            q="大 Boss：你想说「我打算坐火车去北京」，怎么说？",
            opts=["I'm going to go to Beijing by train.", "I'm going to Beijing on train.", "I want Beijing train."],
            ok=0, hint="坐火车用 by train，打算去某地用 be going to"),
  s6_task="这一步我们要做的：打败旅行大 Boss，赢双倍星星！",
  s6_voice="最后的大 Boss 来啦！打算坐火车去北京，用 I'm going to go to Beijing by train。选对奖励两颗星！",
  parent=dict(summary="认识旅行词汇，会用 Where do you want to go? 与 be going to 表达计划。",
              attention="be going to 后接动词原形；坐火车用 by train 而非 on train。",
              tip="本课约 8 分钟；可让孩子用 be going to 说出一个假期的计划。"),
),

dict(
  id="english-4-014", grade=4, term="下册", unit="Unit 4 Hobbies",
  file_unit="Unit4-Hobbies", title="爱好", module="vocab", difficulty="基础",
  summary="爱好词汇与 My hobby is 表达",
  keywords=["爱好", "hobbies", "兴趣"],
  prereq=[], fileName="英语-四下-Unit4-Hobbies-english-4-014-爱好.html",
  scene=dict(h2="兴趣班大集合", text="每个人都有不同的爱好：有人爱读书、有人爱唱歌跳舞、有人爱拼拼图、做模型。你的爱好是什么呢？",
             question="想一想：你会用英语说「我的爱好是读书」吗？", hint="聊聊爱好，找到志同道合的朋友！"),
  s1_task="咱们这一步要做的：学会用英语说自己的爱好！",
  s1_voice="每个人都有不同的爱好：读书、唱歌、跳舞、拼拼图、做模型。Binbin 想知道你的爱好是什么。今天来学爱好的表达。",
  words_title="单词大本营：爱好", words_intro="点一点卡片，认识这些爱好，跟读一遍吧！",
  s2_task="这一步我们要做的：认识爱好的单词，点卡片听发音！",
  s2_voice="爱好有读书、玩滑板、唱歌、跳舞、拼拼图、做模型，还有收集橡皮。点一点卡片，听听它们的英文名字，跟着读一读。",
  words=[dict(e="hobby", z="爱好", em="🎯"), dict(e="reading", z="读书", em="📖"), dict(e="skateboarding", z="玩滑板", em="🛹"),
         dict(e="singing", z="唱歌", em="🎤"), dict(e="dancing", z="跳舞", em="💃"),
         dict(e="doing jigsaw puzzles", z="拼拼图", em="🧩"), dict(e="making models", z="制作模型", em="🚗"),
         dict(e="collecting erasers", z="收集橡皮", em="🧽"), dict(e="different", z="不同的", em="🎨")],
  pattern=dict(title="句型魔法：我的爱好是…", sentence=["My", "hobby", "is", "reading", "."], zh="我的爱好是读书。",
               desc="What are your hobbies? 你的爱好是什么？ ｜ My hobby is ... 我的爱好是… ｜ I like singing and dancing. 我喜欢唱歌和跳舞。"),
  order=dict(zh="帮 Binbin 说「我的爱好是读书」", words=["My", "hobby", "is", "reading", "."], right=[0, 1, 2, 3, 4],
             hint="说爱好用 My hobby is + 动词 ing"),
  s3_task="这一步我们要做的：看 My hobby is 怎么用，再拼一句！",
  s3_voice="说自己的爱好，用 My hobby is 加上爱好的动作，注意要加 ing。看句子拼出来，然后你来拼一句。",
  quiz=[dict(q="「你的爱好是什么？」用英语怎么说？", opts=["What are your hobbies?", "What's your name?", "What do you do?"], ok=0, hint="问爱好用 What are your hobbies?"),
        dict(q="doing jigsaw puzzles 是？", opts=["拼拼图", "玩滑板", "做模型"], ok=0, hint="jigsaw puzzles 是拼图"),
        dict(q="My hobby is dancing. 的意思是？", opts=["我的爱好是跳舞。", "我喜欢唱歌。", "我会跳舞。"], ok=0, hint="hobby 是爱好")],
  s4_task="这一步我们要做的：连闯三道小题，把爱好单词用起来！",
  s4_voice="现在轮到你啦！三道小题，考考爱好的单词和 My hobby is。答对就能得到星星哦。",
  summary_points=[["爱好单词", "reading 读书 · singing 唱歌 · dancing 跳舞 · skateboarding 玩滑板"],
                  ["询问爱好", "What are your hobbies? 你的爱好是什么？"],
                  ["我的爱好", "My hobby is ... 我的爱好是…"]],
  phonics=dict(tip="字母组合 ng 发 /ŋ/，像「嗯」", words="sing 唱 · dancing 跳舞 · reading 读"),
  s5_task="这一步我们要做的：把爱好的单词收进小背包！",
  s5_voice="今天我们学会说自己的爱好：My hobby is 加上动作。下次就能和朋友用英语聊爱好了！",
  boss=dict(title="Boss 关：爱好大挑战", type="mc",
            q="大 Boss：你的爱好是玩滑板，怎么用英语说？",
            opts=["My hobby is skateboarding.", "My hobby is skating.", "I hobby skateboard."],
            ok=0, hint="爱好是…用 My hobby is + 动词 ing"),
  s6_task="这一步我们要做的：打败爱好大 Boss，赢双倍星星！",
  s6_voice="最后的大 Boss 来啦！玩滑板是 skateboarding，用 My hobby is 来表达。选对奖励两颗星！",
  parent=dict(summary="认识爱好词汇，会用 What are your hobbies? 与 My hobby is + ing 表达。",
              attention="hobby 复数 hobbies 易漏 s；动词加 ing（dance→dancing）是重点。",
              tip="本课约 8 分钟；可让孩子用 My hobby is ... 说 3 个爱好。"),
),

dict(
  id="english-4-015", grade=4, term="下册", unit="Unit 5 Free Time",
  file_unit="Unit5-FreeTime", title="空闲时间", module="listen", difficulty="提高",
  summary="空闲活动与 often/sometimes 频率表达",
  keywords=["空闲", "free time", "频率", "often"],
  prereq=[], fileName="英语-四下-Unit5-FreeTime-english-4-015-空闲时间.html",
  scene=dict(h2="我的自由时光", text="写完作业，自由时间到啦！有人看电视、有人听音乐、有人和朋友打球。Binbin 想听听你的自由时光怎么过。",
             question="想一想：你会用英语说「我经常听音乐」吗？", hint="聊一聊你的自由时光！"),
  s1_task="咱们这一步要做的：学会用英语说空闲时间做什么！",
  s1_voice="写完作业，自由时间到啦！有人看电视、有人听音乐、有人和朋友打球。Binbin 想知道你的自由时光怎么过。今天来学这些表达。",
  words_title="单词大本营：空闲时间", words_intro="点一点卡片，认识这些空闲活动，跟读一遍吧！",
  s2_task="这一步我们要做的：认识空闲活动的单词，点卡片听发音！",
  s2_voice="空闲时间可以看电视、和朋友玩、听音乐、读书，还能去公园、打篮球或者睡觉。点一点卡片，跟着读一读。",
  words=[dict(e="free time", z="空闲时间", em="⏰"), dict(e="watch TV", z="看电视", em="📺"),
         dict(e="play with friends", z="和朋友玩", em="🧒"), dict(e="listen to music", z="听音乐", em="🎧"),
         dict(e="read books", z="读书", em="📖"), dict(e="go to the park", z="去公园", em="🌳"),
         dict(e="play basketball", z="打篮球", em="🏀"), dict(e="sleep", z="睡觉", em="😴"), dict(e="sometimes", z="有时", em="🔁")],
  pattern=dict(title="句型魔法：空闲时间我…", sentence=["I", "often", "listen", "to", "music", "in", "my", "free", "time", "."], zh="空闲时间我经常听音乐。",
               desc="What do you do in your free time? 空闲时间你做什么？ ｜ I often ... 我经常… ｜ Sometimes ... 有时…"),
  order=dict(zh="帮 Binbin 说「我经常听音乐」", words=["I", "often", "listen", "to", "music", "."], right=[0, 1, 2, 3, 4, 5],
             hint="经常做某事用 I often ...，听音乐是 listen to music"),
  s3_task="这一步我们要做的：看 often 怎么用，再拼一句！",
  s3_voice="说空闲时间经常做什么，用 I often 加上动作。听音乐是 listen to music，注意有个 to。看句子拼出来，然后你来拼一句。",
  quiz=[dict(q="「空闲时间你做什么？」用英语怎么说？", opts=["What do you do in your free time?", "What do you do after school?", "What's your hobby?"], ok=0, hint="问空闲时间用 in your free time"),
        dict(q="listen to music 是？", opts=["听音乐", "唱歌", "跳舞"], ok=0, hint="listen to music 是听音乐"),
        dict(q="Sometimes I play with my friends. 的意思是？", opts=["有时我和朋友一起玩。", "我经常和朋友玩。", "我不和朋友玩。"], ok=0, hint="sometimes 是有时")],
  s4_task="这一步我们要做的：连闯三道小题，把空闲活动用起来！",
  s4_voice="现在轮到你啦！三道小题，考考空闲活动的单词和频率词。答对就能得到星星哦。",
  summary_points=[["空闲活动", "watch TV 看电视 · listen to music 听音乐 · play basketball 打篮球"],
                  ["询问空闲", "What do you do in your free time? 空闲时间你做什么？"],
                  ["频率词", "often 经常 · sometimes 有时"]],
  phonics=dict(tip="字母组合 ea 常发 /iː/", words="read 读 · tea 茶 · sea 海"),
  s5_task="这一步我们要做的：把空闲活动的单词收进小背包！",
  s5_voice="今天我们学会说空闲时间做什么，还会用 often 和 sometimes 表达频率。下次聊天就能派上用场啦！",
  boss=dict(title="Boss 关：自由时光大挑战", type="mc",
            q="大 Boss：空闲时间你有时打篮球，怎么用英语说？",
            opts=["Sometimes I play basketball in my free time.", "I often play basketball.", "I play basketball and sleep."],
            ok=0, hint="有时用 sometimes，空闲时间用 in my free time"),
  s6_task="这一步我们要做的：打败自由时光大 Boss，赢双倍星星！",
  s6_voice="最后的大 Boss 来啦！有时打篮球，要用 sometimes，还要说 in my free time。选对奖励两颗星！",
  parent=dict(summary="认识空闲活动，会用 What do you do in your free time? 询问、often/sometimes 表达频率。",
              attention="often 与 sometimes 的频率区别；listen to 的 to 不能丢。",
              tip="本课约 8 分钟；可让孩子用 often/sometimes 说自己的自由时光。"),
),

dict(
  id="english-4-016", grade=4, term="下册", unit="Unit 6 Countries",
  file_unit="Unit6-Countries", title="国家", module="vocab", difficulty="基础",
  summary="国家词汇与 Where are you from 表达",
  keywords=["国家", "countries", "来自"],
  prereq=[], fileName="英语-四下-Unit6-Countries-english-4-016-国家.html",
  scene=dict(h2="世界那么大", text="Binbin 认识了一位新朋友，来自遥远的英国。他想知道：你从哪里来？世界各地的人说什么语言？",
             question="想一想：你会用英语说「我来自中国」吗？", hint="环游世界，从学会说国家开始！"),
  s1_task="咱们这一步要做的：学会用英语说自己来自哪里！",
  s1_voice="Binbin 认识了一位来自英国的新朋友。他想知道小伙伴来自哪里。今天来学国家的单词和 Where are you from 的句子。",
  words_title="单词大本营：国家", words_intro="点一点卡片，认识这些国家，跟读一遍吧！",
  s2_task="这一步我们要做的：认识国家的单词，点卡片听发音！",
  s2_voice="世界上的国家有中国、美国、英国、加拿大、澳大利亚、日本、法国和德国。点一点卡片，听听它们的英文名字，跟着读一读。",
  words=[dict(e="China", z="中国", em="🇨🇳"), dict(e="the USA", z="美国", em="🇺🇸"), dict(e="the UK", z="英国", em="🇬🇧"),
         dict(e="Canada", z="加拿大", em="🇨🇦"), dict(e="Australia", z="澳大利亚", em="🇦🇺"), dict(e="Japan", z="日本", em="🇯🇵"),
         dict(e="France", z="法国", em="🇫🇷"), dict(e="Germany", z="德国", em="🇩🇪"), dict(e="capital", z="首都", em="🏛️"),
         dict(e="language", z="语言", em="💬")],
  pattern=dict(title="句型魔法：你来自哪里？", sentence=["I'm", "from", "China", "."], zh="我来自中国。",
               desc="Where are you from? 你来自哪里？ ｜ I'm from ... 我来自…。 ｜ What's the capital of ...? …的首都是哪？"),
  order=dict(zh="帮 Binbin 问「你来自哪里？」", words=["Where", "are", "you", "from", "?"], right=[0, 1, 2, 3, 4],
             hint="问来自哪里用 Where are you from?"),
  s3_task="这一步我们要做的：看 Where are you from 怎么用，再拼一个问句！",
  s3_voice="想知道别人来自哪里，用 Where are you from。回答用 I'm from 加上国家。看句子拼出来，然后你来拼问句。",
  quiz=[dict(q="「你来自哪里？」用英语怎么说？", opts=["Where are you from?", "Where are you?", "What are you from?"], ok=0, hint="问来自哪里用 Where are you from?"),
        dict(q="the UK 是？", opts=["英国", "美国", "中国"], ok=0, hint="the UK 是英国，the USA 是美国"),
        dict(q="I'm from China. 的意思是？", opts=["我来自中国。", "我去中国。", "我住在中国。"], ok=0, hint="from 表示来自")],
  s4_task="这一步我们要做的：连闯三道小题，把国家单词用起来！",
  s4_voice="现在轮到你啦！三道小题，考考国家的单词和 Where are you from。答对就能得到星星哦。",
  summary_points=[["国家单词", "China 中国 · the UK 英国 · the USA 美国 · Canada 加拿大 · Australia 澳大利亚"],
                  ["询问来自", "Where are you from? 你来自哪里？"],
                  ["回答", "I'm from ... 我来自…"]],
  phonics=dict(tip="字母组合 ch 常发 /tʃ/", words="China 中国 · chair 椅子 · lunch 午餐"),
  s5_task="这一步我们要做的：把国家的单词收进小背包！",
  s5_voice="今天我们认识了很多国家，还学会了问别人来自哪里。以后交到外国朋友，你就能用英语打招呼啦！",
  boss=dict(title="Boss 关：国家大挑战", type="mc",
            q="大 Boss：你想问「英国的首都是哪里？」，怎么说？",
            opts=["What's the capital of the UK?", "Where is the UK?", "What language do you speak?"],
            ok=0, hint="问首都用 What's the capital of ...?"),
  s6_task="这一步我们要做的：打败国家大 Boss，赢双倍星星！",
  s6_voice="最后的大 Boss 来啦！它想知道你会不会问首都。用 What's the capital of 加上国家。选对奖励两颗星！",
  parent=dict(summary="认识国家词汇，会用 Where are you from? 询问并用 I'm from ... 回答。",
              attention="英国 the UK / 美国 the USA 前要加 the；from 是来自。",
              tip="本课约 8 分钟；可让孩子用英语介绍自己来自哪里。"),
),
]

# ---------------------------------------------------------------- 模板
HTML_TPL = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title} · AI 教师</title>
<link rel="stylesheet" href="../assets/style.css">
<link rel="stylesheet" href="../assets/course.css">
</head>
<body>
<div class="container">
  <header class="topbar">
    <a class="btn-home" href="index.html">← 英语</a>
    <span class="brand">{unit} <small>{grade}年级·{term}</small></span>
  </header>

  <div class="player">
    <div class="task-line" id="task-line"></div>
    <div class="stage" id="stage"></div>
    <div class="dots" id="dots"></div>
    <div class="controls">
      <button class="cbtn" id="btn-prev">上一步</button>
      <button class="cbtn" id="btn-auto">▶ 自动播放</button>
      <button class="cbtn" id="btn-voice">🔊 语音</button>
      <button class="cbtn main" id="btn-next">下一步</button>
    </div>
    <div class="score-row" id="score-row"></div>
  </div>

  <details class="parent-panel">
    <summary>家长模式（点击展开）</summary>
    <div class="pbody">
      <p><b>本课一句话总结：</b>{ps}</p>
      <p><b>孩子容易走神的地方：</b>{pa}</p>
      <p><b>建议：</b>{pt}</p>
    </div>
  </details>

  <footer class="foot">
    <div>AI 教师 · 英语课件 {id}</div>
  </footer>
</div>

<script src="../assets/voice.js"></script>
<script src="../assets/player-core.js"></script>
<script src="../assets/english-ui.js"></script>
<script>
window.COURSE = {json};
EngUI.launch(window.COURSE);
</script>
</body>
</html>
"""


def html_esc(s):
    return (str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;"))


def main():
    os.makedirs(OUT, exist_ok=True)
    lines = []
    for u in UNITS:
        fn = u["fileName"]
        data = {
            "unit": u["unit"], "title": u["title"], "grade": u["grade"], "term": u["term"],
            "scene": u["scene"],
            "s1_task": u["s1_task"], "s1_voice": u["s1_voice"],
            "words_title": u["words_title"], "words_intro": u["words_intro"],
            "s2_task": u["s2_task"], "s2_voice": u["s2_voice"], "words": u["words"],
            "pattern": u["pattern"], "order": u["order"],
            "s3_task": u["s3_task"], "s3_voice": u["s3_voice"],
            "quiz": u["quiz"],
            "s4_task": u["s4_task"], "s4_voice": u["s4_voice"],
            "summary_points": u["summary_points"], "phonics": u["phonics"],
            "s5_task": u["s5_task"], "s5_voice": u["s5_voice"],
            "boss": u["boss"],
            "s6_task": u["s6_task"], "s6_voice": u["s6_voice"],
            "parent": u["parent"],
        }
        json_str = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
        html = HTML_TPL.format(
            title=html_esc(u["title"]),
            unit=html_esc(u["unit"]),
            grade=u["grade"], term=u["term"],
            ps=html_esc(u["parent"]["summary"]),
            pa=html_esc(u["parent"]["attention"]),
            pt=html_esc(u["parent"]["tip"]),
            id=u["id"],
            json=json_str,
        )
        with open(os.path.join(OUT, fn), "w", encoding="utf-8") as f:
            f.write(html)
        print("生成:", fn)
        lines.append(
            '{ id: "%s", name: "%s", subject: "english", grade: %d, term: "%s", unit: "%s", module: "%s", difficulty: "%s", source: "syllabus", prerequisiteIds: %s, status: "已完成", file: "英语/%s", summary: "%s", keywords: %s, createdAt: "2026-08-30", updatedAt: "2026-08-30" },'
            % (u["id"], u["unit"] + "：" + u["title"], u["grade"], u["term"], u["unit"], u["module"], u["difficulty"],
               json.dumps(u["prereq"], ensure_ascii=False), fn, u["summary"], json.dumps(u["keywords"], ensure_ascii=False))
        )
    print("\n===== knowledge-base.js 条目（复制进 knowledgePoints）=====")
    for l in lines:
        print(l)


if __name__ == "__main__":
    main()
